var species_descriptions =
	{
"Plectorhyncha lanceolata": {id: 0, genus: "Plectorhyncha", species: "lanceolata", description: "Striped Honeyeater"},
"Sula leucogaster": {id: 1, genus: "Sula", species: "leucogaster", description: "Brown Booby"},
"Sula sula": {id: 2, genus: "Sula", species: "sula", description: "Red-footed Booby"},
"Sula dactylatra": {id: 3, genus: "Sula", species: "dactylatra", description: "Masked Booby"},
"Excalfactoria chinensis": {id: 4, genus: "Excalfactoria", species: "chinensis", description: "King Quail"},
"Daphoenositta chrysoptera": {id: 5, genus: "Daphoenositta", species: "chrysoptera", description: "Varied Sittella"},
"Dacelo novaeguineae": {id: 6, genus: "Dacelo", species: "novaeguineae", description: "Laughing Kookaburra"},
"Dacelo leachii": {id: 7, genus: "Dacelo", species: "leachii", description: "Blue-winged Kookaburra"},
"Struthidea cinerea": {id: 8, genus: "Struthidea", species: "cinerea", description: "Apostlebird"},
"Aviceda subcristata": {id: 9, genus: "Aviceda", species: "subcristata", description: "Pacific Baza"},
"Tribonyx mortierii": {id: 10, genus: "Tribonyx", species: "mortierii", description: "Tasmanian Native-hen"},
"Tribonyx ventralis": {id: 11, genus: "Tribonyx", species: "ventralis", description: "Black-tailed Native-hen"},
"Scythrops novaehollandiae": {id: 12, genus: "Scythrops", species: "novaehollandiae", description: "Channel-billed Cuckoo"},
"Ducula mullerii": {id: 13, genus: "Ducula", species: "mullerii", description: "Collared Imperial-Pigeon"},
"Ducula bicolor": {id: 14, genus: "Ducula", species: "bicolor", description: "Pied Imperial-Pigeon"},
"Ducula concinna": {id: 15, genus: "Ducula", species: "concinna", description: "Elegant Imperial-Pigeon"},
"Ducula whartoni": {id: 16, genus: "Ducula", species: "whartoni", description: "Christmas Island Imperial-Pigeon"},
"Strepera fuliginosa": {id: 17, genus: "Strepera", species: "fuliginosa", description: "Black Currawong"},
"Strepera versicolor": {id: 18, genus: "Strepera", species: "versicolor", description: "Grey Currawong"},
"Strepera graculina": {id: 19, genus: "Strepera", species: "graculina", description: "Pied Currawong"},
"Cracticus tibicen": {id: 20, genus: "Cracticus", species: "tibicen", description: "Australian Magpie"},
"Cracticus mentalis": {id: 21, genus: "Cracticus", species: "mentalis", description: "Black-backed Butcherbird"},
"Cracticus quoyi": {id: 22, genus: "Cracticus", species: "quoyi", description: "Black Butcherbird"},
"Cracticus torquatus": {id: 23, genus: "Cracticus", species: "torquatus", description: "Grey Butcherbird"},
"Cracticus nigrogularis": {id: 24, genus: "Cracticus", species: "nigrogularis", description: "Pied Butcherbird"},
"Calonectris leucomelas": {id: 25, genus: "Calonectris", species: "leucomelas", description: "Streaked Shearwater"},
"Porphyrio albus": {id: 26, genus: "Porphyrio", species: "albus", description: "White Gallinule"},
"Porphyrio porphyrio": {id: 27, genus: "Porphyrio", species: "porphyrio", description: "Purple Swamphen"},
"Entomyzon cyanotis": {id: 28, genus: "Entomyzon", species: "cyanotis", description: "Blue-faced Honeyeater"},
"Oxyura australis": {id: 29, genus: "Oxyura", species: "australis", description: "Blue-billed Duck"},
"Poliocephalus poliocephalus": {id: 30, genus: "Poliocephalus", species: "poliocephalus", description: "Hoary-headed Grebe"},
"Phaethon lepturus": {id: 31, genus: "Phaethon", species: "lepturus", description: "White-tailed Tropicbird"},
"Phaethon rubricauda": {id: 32, genus: "Phaethon", species: "rubricauda", description: "Red-tailed Tropicbird"},
"Psophodes cristatus": {id: 33, genus: "Psophodes", species: "cristatus", description: "Chirruping Wedgebill"},
"Psophodes olivaceus": {id: 34, genus: "Psophodes", species: "olivaceus", description: "Eastern Whipbird"},
"Psophodes occidentalis": {id: 35, genus: "Psophodes", species: "occidentalis", description: "Chiming Wedgebill"},
"Psophodes nigrogularis": {id: 36, genus: "Psophodes", species: "nigrogularis", description: "Western Whipbird"},
"Crex crex": {id: 37, genus: "Crex", species: "crex", description: "Corn crake"},
"Eclectus roratus": {id: 38, genus: "Eclectus", species: "roratus", description: "Eclectus Parrot"},
"Certhionyx variegatus": {id: 39, genus: "Certhionyx", species: "variegatus", description: "Pied Honeyeater"},
"Glareola maldivarum": {id: 40, genus: "Glareola", species: "maldivarum", description: "Oriental Pratincole"},
"Conopophila whitei": {id: 41, genus: "Conopophila", species: "whitei", description: "Grey Honeyeater"},
"Conopophila albogularis": {id: 42, genus: "Conopophila", species: "albogularis", description: "Rufous-banded Honeyeater"},
"Conopophila rufogularis": {id: 43, genus: "Conopophila", species: "rufogularis", description: "Rufous-throated Honeyeater"},
"Corcorax melanorhamphos": {id: 44, genus: "Corcorax", species: "melanorhamphos", description: "White-winged Chough"},
"Drymodes superciliaris": {id: 45, genus: "Drymodes", species: "superciliaris", description: "Northern Scrub-robin"},
"Drymodes brunneopygia": {id: 46, genus: "Drymodes", species: "brunneopygia", description: "Southern Scrub-robin"},
"Epthianura tricolor": {id: 47, genus: "Epthianura", species: "tricolor", description: "Crimson Chat"},
"Epthianura aurifrons": {id: 48, genus: "Epthianura", species: "aurifrons", description: "Orange Chat"},
"Epthianura crocea": {id: 49, genus: "Epthianura", species: "crocea", description: "Yellow Chat"},
"Epthianura albifrons": {id: 50, genus: "Epthianura", species: "albifrons", description: "White-fronted Chat"},
"Ceyx azureus": {id: 51, genus: "Ceyx", species: "azureus", description: "Azure Kingfisher"},
"Ceyx pusilla": {id: 52, genus: "Ceyx", species: "pusilla", description: "Little Kingfisher"},
"Psitteuteles versicolor": {id: 53, genus: "Psitteuteles", species: "versicolor", description: "Varied Lorikeet"},
"Himantopus himantopus": {id: 54, genus: "Himantopus", species: "himantopus", description: "Black-winged Stilt"},
"Cygnus olor": {id: 55, genus: "Cygnus", species: "olor", description: "Mute Swan"},
"Cygnus atratus": {id: 56, genus: "Cygnus", species: "atratus", description: "Black Swan"},
"Pyrrholaemus brunneus": {id: 57, genus: "Pyrrholaemus", species: "brunneus", description: "Redthroat"},
"Acanthis flammea": {id: 58, genus: "Acanthis", species: "flammea", description: "Common Redpoll"},
"Sericornis keri": {id: 59, genus: "Sericornis", species: "keri", description: "Atherton Scrubwren"},
"Sericornis humilis": {id: 60, genus: "Sericornis", species: "humilis", description: "Tasmanian Scrubwren"},
"Sericornis magnirostra": {id: 61, genus: "Sericornis", species: "magnirostra", description: "Large-billed Scrubwren"},
"Sericornis beccarii": {id: 62, genus: "Sericornis", species: "beccarii", description: "Tropical Scrubwren"},
"Sericornis citreogularis": {id: 63, genus: "Sericornis", species: "citreogularis", description: "Yellow-throated Scrubwren"},
"Sericornis frontalis": {id: 64, genus: "Sericornis", species: "frontalis", description: "White-browed Scrubwren"},
"Nectarinia jugularis": {id: 65, genus: "Nectarinia", species: "jugularis", description: "Olive-backed Sunbird"},
"Philemon corniculatus": {id: 66, genus: "Philemon", species: "corniculatus", description: "Noisy Friarbird"},
"Philemon buceroides": {id: 67, genus: "Philemon", species: "buceroides", description: "Helmeted Friarbird"},
"Philemon argenticeps": {id: 68, genus: "Philemon", species: "argenticeps", description: "Silver-crowned Friarbird"},
"Philemon citreogularis": {id: 69, genus: "Philemon", species: "citreogularis", description: "Little Friarbird"},
"Purpureicephalus spurius": {id: 70, genus: "Purpureicephalus", species: "spurius", description: "Red-capped Parrot"},
"Arses telescopthalmus": {id: 71, genus: "Arses", species: "telescopthalmus", description: "Frilled Monarch"},
"Arses kaupi": {id: 72, genus: "Arses", species: "kaupi", description: "Pied Monarch"},
"Ailuroedus crassirostris": {id: 73, genus: "Ailuroedus", species: "crassirostris", description: "Green Catbird"},
"Ailuroedus melanotis": {id: 74, genus: "Ailuroedus", species: "melanotis", description: "Spotted Catbird"},
"Zoothera lunulata": {id: 75, genus: "Zoothera", species: "lunulata", description: "Bassian Thrush"},
"Zoothera heinei": {id: 76, genus: "Zoothera", species: "heinei", description: "Russet-tailed Thrush"},
"Milvus migrans": {id: 77, genus: "Milvus", species: "migrans", description: "Black Kite"},
"Rallina tricolor": {id: 78, genus: "Rallina", species: "tricolor", description: "Red-necked Crake"},
"Rallina fasciata": {id: 79, genus: "Rallina", species: "fasciata", description: "Red-legged Crake"},
"Chenonetta jubata": {id: 80, genus: "Chenonetta", species: "jubata", description: "Australian Wood Duck"},
"Chthonicola sagittata": {id: 81, genus: "Chthonicola", species: "sagittata", description: "Speckled Warbler"},
"Columba vitiensis": {id: 82, genus: "Columba", species: "vitiensis", description: "White-throated Pigeon"},
"Columba livia": {id: 83, genus: "Columba", species: "livia", description: "Rock Dove"},
"Columba leucomela": {id: 84, genus: "Columba", species: "leucomela", description: "White-headed Pigeon"},
"Climacteris affinis": {id: 85, genus: "Climacteris", species: "affinis", description: "White-browed Treecreeper"},
"Climacteris picumnus": {id: 86, genus: "Climacteris", species: "picumnus", description: "Brown Treecreeper"},
"Climacteris melanura": {id: 87, genus: "Climacteris", species: "melanura", description: "Black-tailed Treecreeper"},
"Climacteris rufa": {id: 88, genus: "Climacteris", species: "rufa", description: "Rufous Treecreeper"},
"Climacteris erythrops": {id: 89, genus: "Climacteris", species: "erythrops", description: "Red-browed Treecreeper"},
"Acanthiza robustirostris": {id: 90, genus: "Acanthiza", species: "robustirostris", description: "Slaty-backed Thornbill"},
"Acanthiza katherina": {id: 91, genus: "Acanthiza", species: "katherina", description: "Mountain Thornbill"},
"Acanthiza iredalei": {id: 92, genus: "Acanthiza", species: "iredalei", description: "Slender-billed Thornbill"},
"Acanthiza apicalis": {id: 93, genus: "Acanthiza", species: "apicalis", description: "Inland Thornbill"},
"Acanthiza ewingii": {id: 94, genus: "Acanthiza", species: "ewingii", description: "Tasmanian Thornbill"},
"Acanthiza inornata": {id: 95, genus: "Acanthiza", species: "inornata", description: "Western Thornbill"},
"Acanthiza pusilla": {id: 96, genus: "Acanthiza", species: "pusilla", description: "Brown Thornbill"},
"Acanthiza reguloides": {id: 97, genus: "Acanthiza", species: "reguloides", description: "Buff-rumped Thornbill"},
"Acanthiza chrysorrhoa": {id: 98, genus: "Acanthiza", species: "chrysorrhoa", description: "Yellow-rumped Thornbill"},
"Acanthiza uropygialis": {id: 99, genus: "Acanthiza", species: "uropygialis", description: "Chestnut-rumped Thornbill"},
"Acanthiza lineata": {id: 100, genus: "Acanthiza", species: "lineata", description: "Striated Thornbill"},
"Acanthiza nana": {id: 101, genus: "Acanthiza", species: "nana", description: "Yellow Thornbill"},
"Struthio camelus": {id: 102, genus: "Struthio", species: "camelus", description: "Ostrich"},
"Heteromyias cinereifrons": {id: 103, genus: "Heteromyias", species: "cinereifrons", description: "Grey-headed Robin"},
"Alauda arvensis": {id: 104, genus: "Alauda", species: "arvensis", description: "Eurasian Skylark"},
"Origma solitaria": {id: 105, genus: "Origma", species: "solitaria", description: "Rockwarbler"},
"Lopholaimus antarcticus": {id: 106, genus: "Lopholaimus", species: "antarcticus", description: "Topknot Pigeon"},
"Procelsterna cerulea": {id: 107, genus: "Procelsterna", species: "cerulea", description: "Grey Ternlet"},
"Phylloscopus borealis": {id: 108, genus: "Phylloscopus", species: "borealis", description: "Arctic Warbler"},
"Delichon dasypus": {id: 109, genus: "Delichon", species: "dasypus", description: "Asian House Martin"},
"Dicrurus bracteatus": {id: 110, genus: "Dicrurus", species: "bracteatus", description: "Spangled Drongo"},
"Stictonetta naevosa": {id: 111, genus: "Stictonetta", species: "naevosa", description: "Freckled Duck"},
"Erythrogonys cinctus": {id: 112, genus: "Erythrogonys", species: "cinctus", description: "Red-kneed Dotterel"},
"Stagonopleura oculata": {id: 113, genus: "Stagonopleura", species: "oculata", description: "Red-eared Firetail"},
"Stagonopleura guttata": {id: 114, genus: "Stagonopleura", species: "guttata", description: "Diamond Firetail"},
"Stagonopleura bella": {id: 115, genus: "Stagonopleura", species: "bella", description: "Beautiful Firetail"},
"Eudyptes chrysolophus": {id: 116, genus: "Eudyptes", species: "chrysolophus", description: "Macaroni Penguin"},
"Eudyptes pachyrhynchus": {id: 117, genus: "Eudyptes", species: "pachyrhynchus", description: "Fiordland Penguin"},
"Eudyptes chrysocome": {id: 118, genus: "Eudyptes", species: "chrysocome", description: "Rockhopper Penguin"},
"Eudyptes sclateri": {id: 119, genus: "Eudyptes", species: "sclateri", description: "Erect-crested Penguin"},
"Aplornis cantoroides": {id: 120, genus: "Aplornis", species: "cantoroides", description: "Singing Starling"},
"Aplornis metallica": {id: 121, genus: "Aplornis", species: "metallica", description: "Metallic Starling"},
"Aplornis fusca": {id: 122, genus: "Aplornis", species: "fusca", description: "Tasman Starling"},
"Dasyornis broadbenti": {id: 123, genus: "Dasyornis", species: "broadbenti", description: "Rufous Bristlebird"},
"Dasyornis longirostris": {id: 124, genus: "Dasyornis", species: "longirostris", description: "Western Bristlebird"},
"Dasyornis brachypterus": {id: 125, genus: "Dasyornis", species: "brachypterus", description: "Eastern Bristlebird"},
"Aphelocephala pectoralis": {id: 126, genus: "Aphelocephala", species: "pectoralis", description: "Chestnut-breasted Whiteface"},
"Aphelocephala nigricincta": {id: 127, genus: "Aphelocephala", species: "nigricincta", description: "Banded Whiteface"},
"Aphelocephala leucopsis": {id: 128, genus: "Aphelocephala", species: "leucopsis", description: "Southern Whiteface"},
"Falco peregrinus": {id: 129, genus: "Falco", species: "peregrinus", description: "Peregrine Falcon"},
"Falco subniger": {id: 130, genus: "Falco", species: "subniger", description: "Black Falcon"},
"Falco cenchroides": {id: 131, genus: "Falco", species: "cenchroides", description: "Nankeen Kestrel"},
"Falco longipennis": {id: 132, genus: "Falco", species: "longipennis", description: "Australian Hobby"},
"Falco hypoleucos": {id: 133, genus: "Falco", species: "hypoleucos", description: "Grey Falcon"},
"Falco berigora": {id: 134, genus: "Falco", species: "berigora", description: "Brown Falcon"},
"Ashbyia lovensis": {id: 135, genus: "Ashbyia", species: "lovensis", description: "Gibberbird"},
"Petrophassa rufipennis": {id: 136, genus: "Petrophassa", species: "rufipennis", description: "Chestnut-quilled Rock-Pigeon"},
"Petrophassa albipennis": {id: 137, genus: "Petrophassa", species: "albipennis", description: "White-quilled Rock-Pigeon"},
"Rostratula australis": {id: 138, genus: "Rostratula", species: "australis", description: "Australian Painted Snipe"},
"Hirundo rustica": {id: 139, genus: "Hirundo", species: "rustica", description: "Barn Swallow"},
"Hirundo neoxena": {id: 140, genus: "Hirundo", species: "neoxena", description: "Welcome Swallow"},
"Halobaena caerulea": {id: 141, genus: "Halobaena", species: "caerulea", description: "Blue Petrel"},
"Cecropis daurica": {id: 142, genus: "Cecropis", species: "daurica", description: "Red-rumped Swallow"},
"Smicrornis brevirostris": {id: 143, genus: "Smicrornis", species: "brevirostris", description: "Weebill"},
"Syma torotoro": {id: 144, genus: "Syma", species: "torotoro", description: "Yellow-billed Kingfisher"},
"Butorides striata": {id: 145, genus: "Butorides", species: "striata", description: "Striated Heron"},
"Haliastur sphenurus": {id: 146, genus: "Haliastur", species: "sphenurus", description: "Whistling Kite"},
"Haliastur indus": {id: 147, genus: "Haliastur", species: "indus", description: "Brahminy Kite"},
"Geoffroyus geoffroyi": {id: 148, genus: "Geoffroyus", species: "geoffroyi", description: "Red-cheeked Parrot"},
"Morus serrator": {id: 149, genus: "Morus", species: "serrator", description: "Australasian Gannet"},
"Morus capensis": {id: 150, genus: "Morus", species: "capensis", description: "Cape Gannet"},
"Pelecanus conspicillatus": {id: 151, genus: "Pelecanus", species: "conspicillatus", description: "Australian Pelican"},
"Symposiarchus trivirgatus": {id: 152, genus: "Symposiarchus", species: "trivirgatus", description: "Spectacled Monarch"},
"Haematopus fuliginosus": {id: 153, genus: "Haematopus", species: "fuliginosus", description: "Sooty Oystercatcher"},
"Haematopus longirostris": {id: 154, genus: "Haematopus", species: "longirostris", description: "Australian Pied Oystercatcher"},
"Haematopus finschi": {id: 155, genus: "Haematopus", species: "finschi", description: "South Island Pied Oystercatcher"},
"Hieraaetus morphnoides": {id: 156, genus: "Hieraaetus", species: "morphnoides", description: "Little Eagle"},
"Petroica boodang": {id: 157, genus: "Petroica", species: "boodang", description: "Scarlet Robin"},
"Petroica rosea": {id: 158, genus: "Petroica", species: "rosea", description: "Rose Robin"},
"Petroica goodenovii": {id: 159, genus: "Petroica", species: "goodenovii", description: "Red-capped Robin"},
"Petroica multicolor": {id: 160, genus: "Petroica", species: "multicolor", description: "Pacific Robin"},
"Petroica rodinogaster": {id: 161, genus: "Petroica", species: "rodinogaster", description: "Pink Robin"},
"Petroica phoenicea": {id: 162, genus: "Petroica", species: "phoenicea", description: "Flame Robin"},
"Pseudobulweria rostrata": {id: 163, genus: "Pseudobulweria", species: "rostrata", description: "Tahiti Petrel"},
"Ardeola speciosa": {id: 164, genus: "Ardeola", species: "speciosa", description: "Javan Pond Heron"},
"Ardeola bacchus": {id: 165, genus: "Ardeola", species: "bacchus", description: "Chinese Pond Heron"},
"Cisticola juncidus": {id: 166, genus: "Cisticola", species: "juncidus", description: "Zitting Cisticola"},
"Cisticola exilis": {id: 167, genus: "Cisticola", species: "exilis", description: "Golden-headed Cisticola"},
"Hydroprogne caspia": {id: 168, genus: "Hydroprogne", species: "caspia", description: "Caspian Tern"},
"Pitta versicolor": {id: 169, genus: "Pitta", species: "versicolor", description: "Noisy Pitta"},
"Pitta moluccensis": {id: 170, genus: "Pitta", species: "moluccensis", description: "Blue-winged Pitta"},
"Pitta iris": {id: 171, genus: "Pitta", species: "iris", description: "Rainbow Pitta"},
"Pitta erythrogaster": {id: 172, genus: "Pitta", species: "erythrogaster", description: "Red-bellied Pitta"},
"Calidris ruficollis": {id: 173, genus: "Calidris", species: "ruficollis", description: "Red-necked Stint"},
"Calidris ferruginea": {id: 174, genus: "Calidris", species: "ferruginea", description: "Curlew Sandpiper"},
"Calidris canutus": {id: 175, genus: "Calidris", species: "canutus", description: "Red Knot"},
"Calidris minuta": {id: 176, genus: "Calidris", species: "minuta", description: "Little Stint"},
"Calidris tenuirostris": {id: 177, genus: "Calidris", species: "tenuirostris", description: "Great Knot"},
"Calidris melanotos": {id: 178, genus: "Calidris", species: "melanotos", description: "Pectoral Sandpiper"},
"Calidris alpina": {id: 179, genus: "Calidris", species: "alpina", description: "Dunlin"},
"Calidris alba": {id: 180, genus: "Calidris", species: "alba", description: "Sanderling"},
"Calidris fuscicollis": {id: 181, genus: "Calidris", species: "fuscicollis", description: "White-rumped Sandpiper"},
"Calidris bairdii": {id: 182, genus: "Calidris", species: "bairdii", description: "Baird's Sandpiper"},
"Calidris himantopus": {id: 183, genus: "Calidris", species: "himantopus", description: "Stilt Sandpiper"},
"Calidris subminuta": {id: 184, genus: "Calidris", species: "subminuta", description: "Long-toed Stint"},
"Calidris acuminata": {id: 185, genus: "Calidris", species: "acuminata", description: "Sharp-tailed Sandpiper"},
"Spheniscus magellanicus": {id: 186, genus: "Spheniscus", species: "magellanicus", description: "Magellanic Penguin"},
"Carternornis leucotis": {id: 187, genus: "Carternornis", species: "leucotis", description: "White-eared Monarch"},
"Limnodromus griseus": {id: 188, genus: "Limnodromus", species: "griseus", description: "Short-billed Dowitcher"},
"Limnodromus semipalmatus": {id: 189, genus: "Limnodromus", species: "semipalmatus", description: "Asian Dowitcher"},
"Charadrius leschenaultii": {id: 190, genus: "Charadrius", species: "leschenaultii", description: "Greater Sand Plover"},
"Charadrius alexandrinus": {id: 191, genus: "Charadrius", species: "alexandrinus", description: "Kentish Plover"},
"Charadrius asiaticus": {id: 192, genus: "Charadrius", species: "asiaticus", description: "Caspian Plover"},
"Charadrius mongolus": {id: 193, genus: "Charadrius", species: "mongolus", description: "Lesser Sand Plover"},
"Charadrius australis": {id: 194, genus: "Charadrius", species: "australis", description: "Inland Dotterel"},
"Charadrius dubius": {id: 195, genus: "Charadrius", species: "dubius", description: "Little Ringed Plover"},
"Charadrius hiaticula": {id: 196, genus: "Charadrius", species: "hiaticula", description: "Ringed Plover"},
"Charadrius ruficapillus": {id: 197, genus: "Charadrius", species: "ruficapillus", description: "Red-capped Plover"},
"Charadrius veredus": {id: 198, genus: "Charadrius", species: "veredus", description: "Oriental Plover"},
"Charadrius bicinctus": {id: 199, genus: "Charadrius", species: "bicinctus", description: "Double-banded Plover"},
"Todiramphus chloris": {id: 200, genus: "Todiramphus", species: "chloris", description: "Collared Kingfisher"},
"Todiramphus pyrrhopygius": {id: 201, genus: "Todiramphus", species: "pyrrhopygius", description: "Red-backed Kingfisher"},
"Todiramphus macleayii": {id: 202, genus: "Todiramphus", species: "macleayii", description: "Forest Kingfisher"},
"Todiramphus sanctus": {id: 203, genus: "Todiramphus", species: "sanctus", description: "Sacred Kingfisher"},
"Pelecanoides urinatrix": {id: 204, genus: "Pelecanoides", species: "urinatrix", description: "Common Diving-Petrel"},
"Pelecanoides georgicus": {id: 205, genus: "Pelecanoides", species: "georgicus", description: "South Georgian Diving-Petrel"},
"Garrodia nereis": {id: 206, genus: "Garrodia", species: "nereis", description: "Grey-backed Storm-Petrel"},
"Collocalia esculenta": {id: 207, genus: "Collocalia", species: "esculenta", description: "Glossy Swiftlet"},
"Collocalia linchi": {id: 208, genus: "Collocalia", species: "linchi", description: "Linchi Swiftlet"},
"Tregellasia leucops": {id: 209, genus: "Tregellasia", species: "leucops", description: "White-faced Robin"},
"Tregellasia capito": {id: 210, genus: "Tregellasia", species: "capito", description: "Pale-yellow Robin"},
"Thalassoica antarctica": {id: 211, genus: "Thalassoica", species: "antarctica", description: "Antarctic Petrel"},
"Dromaius baudinianus": {id: 212, genus: "Dromaius", species: "baudinianus", description: "Kangaroo Island Emu"},
"Dromaius novaehollandiae": {id: 213, genus: "Dromaius", species: "novaehollandiae", description: "Emu"},
"Dromaius ater": {id: 214, genus: "Dromaius", species: "ater", description: "King Island Emu"},
"Phalaropus lobatus": {id: 215, genus: "Phalaropus", species: "lobatus", description: "Red-necked Phalarope"},
"Phalaropus fulicarius": {id: 216, genus: "Phalaropus", species: "fulicarius", description: "Grey Phalarope"},
"Pernis ptilorynchus": {id: 217, genus: "Pernis", species: "ptilorynchus", description: "Oriental Honey-buzzard"},
"Limicola falcinellus": {id: 218, genus: "Limicola", species: "falcinellus", description: "Broad-billed Sandpiper"},
"Gelochelidon nilotica": {id: 219, genus: "Gelochelidon", species: "nilotica", description: "Gull-billed Tern"},
"Procellaria parkinsoni": {id: 220, genus: "Procellaria", species: "parkinsoni", description: "Black Petrel"},
"Procellaria cinerea": {id: 221, genus: "Procellaria", species: "cinerea", description: "Grey Petrel"},
"Procellaria westlandica": {id: 222, genus: "Procellaria", species: "westlandica", description: "Westland Petrel"},
"Procellaria aequinoctialis": {id: 223, genus: "Procellaria", species: "aequinoctialis", description: "White-chinned Petrel"},
"Poephila cincta": {id: 224, genus: "Poephila", species: "cincta", description: "Black-throated Finch"},
"Poephila acuticauda": {id: 225, genus: "Poephila", species: "acuticauda", description: "Long-tailed Finch"},
"Poephila personata": {id: 226, genus: "Poephila", species: "personata", description: "Masked Finch"},
"Pica pica": {id: 227, genus: "Pica", species: "pica", description: "Black-billed Magpie"},
"Nymphicus hollandicus": {id: 228, genus: "Nymphicus", species: "hollandicus", description: "Cockatiel"},
"Pachyptila vittata": {id: 229, genus: "Pachyptila", species: "vittata", description: "Broad-billed Prion"},
"Pachyptila crassirostris": {id: 230, genus: "Pachyptila", species: "crassirostris", description: "Fulmar Prion"},
"Pachyptila turtur": {id: 231, genus: "Pachyptila", species: "turtur", description: "Fairy Prion"},
"Pachyptila salvini": {id: 232, genus: "Pachyptila", species: "salvini", description: "Salvin's Prion"},
"Pachyptila belcheri": {id: 233, genus: "Pachyptila", species: "belcheri", description: "Slender-billed Prion"},
"Pachyptila desolata": {id: 234, genus: "Pachyptila", species: "desolata", description: "Antarctic Prion"},
"Tanysiptera sylvia": {id: 235, genus: "Tanysiptera", species: "sylvia", description: "Buff-breasted Paradise-Kingfisher"},
"Lanius cristatus": {id: 236, genus: "Lanius", species: "cristatus", description: "Brown Shrike"},
"Lanius tigrinus": {id: 237, genus: "Lanius", species: "tigrinus", description: "Tiger Shrike"},
"Pachycephala melanura": {id: 238, genus: "Pachycephala", species: "melanura", description: "Mangrove Golden Whistler"},
"Pachycephala inornata": {id: 239, genus: "Pachycephala", species: "inornata", description: "Gilbert's Whistler"},
"Pachycephala olivacea": {id: 240, genus: "Pachycephala", species: "olivacea", description: "Olive Whistler"},
"Pachycephala simplex": {id: 241, genus: "Pachycephala", species: "simplex", description: "Grey Whistler"},
"Pachycephala rufiventris": {id: 242, genus: "Pachycephala", species: "rufiventris", description: "Rufous Whistler"},
"Pachycephala pectoralis": {id: 243, genus: "Pachycephala", species: "pectoralis", description: "Golden Whistler"},
"Pachycephala rufogularis": {id: 244, genus: "Pachycephala", species: "rufogularis", description: "Red-lored Whistler"},
"Pachycephala lanioides": {id: 245, genus: "Pachycephala", species: "lanioides", description: "White-breasted Whistler"},
"Burhinus grallarius": {id: 246, genus: "Burhinus", species: "grallarius", description: "Bush Stone-curlew"},
"Heteromunia pectoralis": {id: 247, genus: "Heteromunia", species: "pectoralis", description: "Pictorella Mannikin"},
"Lugensa brevirostris": {id: 248, genus: "Lugensa", species: "brevirostris", description: "Kerguelen Petrel"},
"Pycnonotus jocosus": {id: 249, genus: "Pycnonotus", species: "jocosus", description: "Red-whiskered Bulbul"},
"Irediparra gallinacea": {id: 250, genus: "Irediparra", species: "gallinacea", description: "Comb-crested Jacana"},
"Pycnoptilus floccosus": {id: 251, genus: "Pycnoptilus", species: "floccosus", description: "Pilotbird"},
"Emblema pictum": {id: 252, genus: "Emblema", species: "pictum", description: "Painted Finch"},
"Meliphaga notata": {id: 253, genus: "Meliphaga", species: "notata", description: "Yellow-spotted Honeyeater"},
"Meliphaga gracilis": {id: 254, genus: "Meliphaga", species: "gracilis", description: "Graceful Honeyeater"},
"Meliphaga albilineata": {id: 255, genus: "Meliphaga", species: "albilineata", description: "White-lined Honeyeater"},
"Meliphaga lewinii": {id: 256, genus: "Meliphaga", species: "lewinii", description: "Lewin's Honeyeater"},
"Meliphaga fordiana": {id: 257, genus: "Meliphaga", species: "fordiana", description: "Kimberley Honeyeater"},
"Pterodroma nigripennis": {id: 258, genus: "Pterodroma", species: "nigripennis", description: "Black-winged Petrel"},
"Pterodroma occulta": {id: 259, genus: "Pterodroma", species: "occulta", description: "Vanuatu Petrel"},
"Pterodroma cervicalis": {id: 260, genus: "Pterodroma", species: "cervicalis", description: "White-necked Petrel"},
"Pterodroma mollis": {id: 261, genus: "Pterodroma", species: "mollis", description: "Soft-plumaged Petrel"},
"Pterodroma externa": {id: 262, genus: "Pterodroma", species: "externa", description: "Juan Fernandez Petrel"},
"Pterodroma incerta": {id: 263, genus: "Pterodroma", species: "incerta", description: "Atlantic Petrel"},
"Pterodroma baraui": {id: 264, genus: "Pterodroma", species: "baraui", description: "Barau's Petrel"},
"Pterodroma leucoptera": {id: 265, genus: "Pterodroma", species: "leucoptera", description: "Gould's Petrel"},
"Pterodroma inexpectata": {id: 266, genus: "Pterodroma", species: "inexpectata", description: "Mottled Petrel"},
"Pterodroma cookii": {id: 267, genus: "Pterodroma", species: "cookii", description: "Cook's Petrel"},
"Pterodroma macroptera": {id: 268, genus: "Pterodroma", species: "macroptera", description: "Great-winged Petrel"},
"Pterodroma neglecta": {id: 269, genus: "Pterodroma", species: "neglecta", description: "Kermadec Petrel"},
"Pterodroma heraldica": {id: 270, genus: "Pterodroma", species: "heraldica", description: "Herald Petrel"},
"Pterodroma solandri": {id: 271, genus: "Pterodroma", species: "solandri", description: "Providence Petrel"},
"Pterodroma lessonii": {id: 272, genus: "Pterodroma", species: "lessonii", description: "White-headed Petrel"},
"Philomachus pugnax": {id: 273, genus: "Philomachus", species: "pugnax", description: "Ruff"},
"Egretta picata": {id: 274, genus: "Egretta", species: "picata", description: "Pied Heron"},
"Egretta novaehollandiae": {id: 275, genus: "Egretta", species: "novaehollandiae", description: "White-faced Heron"},
"Egretta sacra": {id: 276, genus: "Egretta", species: "sacra", description: "Eastern Reef Egret"},
"Egretta garzetta": {id: 277, genus: "Egretta", species: "garzetta", description: "Little Egret"},
"Eudyptula minor": {id: 278, genus: "Eudyptula", species: "minor", description: "Little Penguin"},
"Macronectes giganteus": {id: 279, genus: "Macronectes", species: "giganteus", description: "Southern Giant-Petrel"},
"Macronectes halli": {id: 280, genus: "Macronectes", species: "halli", description: "Northern Giant-Petrel"},
"Leucocarbo verrucosus": {id: 281, genus: "Leucocarbo", species: "verrucosus", description: "Kerguelen Shag"},
"Leucocarbo atriceps": {id: 282, genus: "Leucocarbo", species: "atriceps", description: "Imperial Shag"},
"Amblyornis newtonianus": {id: 283, genus: "Amblyornis", species: "newtonianus", description: "Golden Bowerbird"},
"Cissomela pectoralis": {id: 284, genus: "Cissomela", species: "pectoralis", description: "Banded Honeyeater"},
"Bartramia longicauda": {id: 285, genus: "Bartramia", species: "longicauda", description: "Upland Sandpiper"},
"Threskiornis spinicollis": {id: 286, genus: "Threskiornis", species: "spinicollis", description: "Straw-necked Ibis"},
"Threskiornis molucca": {id: 287, genus: "Threskiornis", species: "molucca", description: "Australian White Ibis"},
"Tadorna variegata": {id: 288, genus: "Tadorna", species: "variegata", description: "Paradise Shelduck"},
"Tadorna radjah": {id: 289, genus: "Tadorna", species: "radjah", description: "Radjah Shelduck"},
"Tadorna tadornoides": {id: 290, genus: "Tadorna", species: "tadornoides", description: "Australian Shelduck"},
"Aptenodytes forsteri": {id: 291, genus: "Aptenodytes", species: "forsteri", description: "Emperor Penguin"},
"Aptenodytes patagonicus": {id: 292, genus: "Aptenodytes", species: "patagonicus", description: "King Penguin"},
"Xanthotis macleayanus": {id: 293, genus: "Xanthotis", species: "macleayanus", description: "Macleay's Honeyeater"},
"Xanthotis flaviventer": {id: 294, genus: "Xanthotis", species: "flaviventer", description: "Tawny-breasted Honeyeater"},
"Malacorhynchus membranaceus": {id: 295, genus: "Malacorhynchus", species: "membranaceus", description: "Pink-eared Duck"},
"Ptilonorhynchus maculatus": {id: 296, genus: "Ptilonorhynchus", species: "maculatus", description: "Spotted Bowerbird"},
"Ptilonorhynchus nuchalis": {id: 297, genus: "Ptilonorhynchus", species: "nuchalis", description: "Great Bowerbird"},
"Ptilonorhynchus violaceus": {id: 298, genus: "Ptilonorhynchus", species: "violaceus", description: "Satin Bowerbird"},
"Ptilonorhynchus cerviniventris": {id: 299, genus: "Ptilonorhynchus", species: "cerviniventris", description: "Fawn-breasted Bowerbird"},
"Ptilonorhynchus guttatus": {id: 300, genus: "Ptilonorhynchus", species: "guttatus", description: "Western Bowerbird"},
"Fregata andrewsi": {id: 301, genus: "Fregata", species: "andrewsi", description: "Christmas Island Frigatebird"},
"Fregata minor": {id: 302, genus: "Fregata", species: "minor", description: "Great Frigatebird"},
"Fregata ariel": {id: 303, genus: "Fregata", species: "ariel", description: "Lesser Frigatebird"},
"Acanthornis magna": {id: 304, genus: "Acanthornis", species: "magna", description: "Scrubtit"},
"Geophaps scripta": {id: 305, genus: "Geophaps", species: "scripta", description: "Squatter Pigeon"},
"Geophaps smithii": {id: 306, genus: "Geophaps", species: "smithii", description: "Partridge Pigeon"},
"Geophaps plumifera": {id: 307, genus: "Geophaps", species: "plumifera", description: "Spinifex Pigeon"},
"Alectura lathami": {id: 308, genus: "Alectura", species: "lathami", description: "Australian Brush-turkey"},
"Chroicocephalus novaehollandiae": {id: 309, genus: "Chroicocephalus", species: "novaehollandiae", description: "Silver Gull"},
"Chroicocephalus ridibundus": {id: 310, genus: "Chroicocephalus", species: "ridibundus", description: "Black-headed Gull"},
"Diomedea epomophora": {id: 311, genus: "Diomedea", species: "epomophora", description: "Royal Albatross"},
"Diomedea exulans": {id: 312, genus: "Diomedea", species: "exulans", description: "Wandering Albatross"},
"Phasianus colchicus": {id: 313, genus: "Phasianus", species: "colchicus", description: "Common Pheasant"},
"Myzomela erythrocephala": {id: 314, genus: "Myzomela", species: "erythrocephala", description: "Red-headed Honeyeater"},
"Myzomela obscura": {id: 315, genus: "Myzomela", species: "obscura", description: "Dusky Honeyeater"},
"Myzomela sanguinolenta": {id: 316, genus: "Myzomela", species: "sanguinolenta", description: "Scarlet Honeyeater"},
"Dendrocygna arcuata": {id: 317, genus: "Dendrocygna", species: "arcuata", description: "Wandering Whistling-Duck"},
"Dendrocygna guttata": {id: 318, genus: "Dendrocygna", species: "guttata", description: "Spotted Whistling-Duck"},
"Dendrocygna eytoni": {id: 319, genus: "Dendrocygna", species: "eytoni", description: "Plumed Whistling-Duck"},
"Coturnix ypsilophora": {id: 320, genus: "Coturnix", species: "ypsilophora", description: "Brown Quail"},
"Coturnix pectoralis": {id: 321, genus: "Coturnix", species: "pectoralis", description: "Stubble Quail"},
"Thalassarche chlororhynchos": {id: 322, genus: "Thalassarche", species: "chlororhynchos", description: "Yellow-nosed Albatross"},
"Thalassarche melanophris": {id: 323, genus: "Thalassarche", species: "melanophris", description: "Black-browed Albatross"},
"Thalassarche bulleri": {id: 324, genus: "Thalassarche", species: "bulleri", description: "Buller's Albatross"},
"Thalassarche cauta": {id: 325, genus: "Thalassarche", species: "cauta", description: "Shy Albatross"},
"Thalassarche chrysostoma": {id: 326, genus: "Thalassarche", species: "chrysostoma", description: "Grey-headed Albatross"},
"Cacatua galerita": {id: 327, genus: "Cacatua", species: "galerita", description: "Sulphur-crested Cockatoo"},
"Cacatua pastinator": {id: 328, genus: "Cacatua", species: "pastinator", description: "Western Corella"},
"Cacatua tenuirostris": {id: 329, genus: "Cacatua", species: "tenuirostris", description: "Long-billed Corella"},
"Cacatua sanguinea": {id: 330, genus: "Cacatua", species: "sanguinea", description: "Little Corella"},
"Eulabeornis castaneoventris": {id: 331, genus: "Eulabeornis", species: "castaneoventris", description: "Chestnut Rail"},
"Mearnsia novaeguineae": {id: 332, genus: "Mearnsia", species: "novaeguineae", description: "Papuan Spine-tailed Swift"},
"Melithreptus affinis": {id: 333, genus: "Melithreptus", species: "affinis", description: "Black-headed Honeyeater"},
"Melithreptus lunatus": {id: 334, genus: "Melithreptus", species: "lunatus", description: "White-naped Honeyeater"},
"Melithreptus gularis": {id: 335, genus: "Melithreptus", species: "gularis", description: "Black-chinned Honeyeater"},
"Melithreptus albogularis": {id: 336, genus: "Melithreptus", species: "albogularis", description: "White-throated Honeyeater"},
"Melithreptus brevirostris": {id: 337, genus: "Melithreptus", species: "brevirostris", description: "Brown-headed Honeyeater"},
"Melithreptus validirostris": {id: 338, genus: "Melithreptus", species: "validirostris", description: "Strong-billed Honeyeater"},
"Lophochroa leadbeateri": {id: 339, genus: "Lophochroa", species: "leadbeateri", description: "Major Mitchell's Cockatoo"},
"Ardenna creatopus": {id: 340, genus: "Ardenna", species: "creatopus", description: "Pink-footed Shearwater"},
"Ardenna tenuirostris": {id: 341, genus: "Ardenna", species: "tenuirostris", description: "Short-tailed Shearwater"},
"Ardenna grisea": {id: 342, genus: "Ardenna", species: "grisea", description: "Sooty Shearwater"},
"Ardenna bulleri": {id: 343, genus: "Ardenna", species: "bulleri", description: "Buller's Shearwater"},
"Ardenna gravis": {id: 344, genus: "Ardenna", species: "gravis", description: "Great Shearwater"},
"Ardenna carneipes": {id: 345, genus: "Ardenna", species: "carneipes", description: "Flesh-footed Shearwater"},
"Ardenna pacifica": {id: 346, genus: "Ardenna", species: "pacifica", description: "Wedge-tailed Shearwater"},
"Macropygia amboinensis": {id: 347, genus: "Macropygia", species: "amboinensis", description: "Brown Cuckoo-Dove"},
"Tachybaptus ruficollis": {id: 348, genus: "Tachybaptus", species: "ruficollis", description: "Little Grebe"},
"Tachybaptus novaehollandiaeeeee": {id: 349, genus: "Tachybaptus", species: "novaehollandiaeeeee", description: "Australasian Grebe"},
"Polytelis anthopeplus": {id: 350, genus: "Polytelis", species: "anthopeplus", description: "Regent Parrot"},
"Polytelis swainsonii": {id: 351, genus: "Polytelis", species: "swainsonii", description: "Superb Parrot"},
"Polytelis alexandrae": {id: 352, genus: "Polytelis", species: "alexandrae", description: "Princess Parrot"},
"Dicaeum geelvinkianum": {id: 353, genus: "Dicaeum", species: "geelvinkianum", description: "Red-capped Flowerpecker"},
"Dicaeum hirundinaceum": {id: 354, genus: "Dicaeum", species: "hirundinaceum", description: "Mistletoebird"},
"Eopsaltria australis": {id: 355, genus: "Eopsaltria", species: "australis", description: "Eastern Yellow Robin"},
"Eopsaltria georgiana": {id: 356, genus: "Eopsaltria", species: "georgiana", description: "White-breasted Robin"},
"Eopsaltria griseogularis": {id: 357, genus: "Eopsaltria", species: "griseogularis", description: "Western Yellow Robin"},
"Actitis hypoleucos": {id: 358, genus: "Actitis", species: "hypoleucos", description: "Common Sandpiper"},
"Microcarbo melanoleucos": {id: 359, genus: "Microcarbo", species: "melanoleucos", description: "Little Pied Cormorant"},
"Motacilla tschutschensis": {id: 360, genus: "Motacilla", species: "tschutschensis", description: "Eastern Yellow Wagtail"},
"Motacilla alba": {id: 361, genus: "Motacilla", species: "alba", description: "White Wagtail"},
"Motacilla citreola": {id: 362, genus: "Motacilla", species: "citreola", description: "Citrine Wagtail"},
"Motacilla cinerea": {id: 363, genus: "Motacilla", species: "cinerea", description: "Grey Wagtail"},
"Motacilla taivana": {id: 364, genus: "Motacilla", species: "taivana", description: "Green-headed Yellow Wagtail"},
"Vanellus tricolor": {id: 365, genus: "Vanellus", species: "tricolor", description: "Banded Lapwing"},
"Vanellus cinereus": {id: 366, genus: "Vanellus", species: "cinereus", description: "Grey-headed Lapwing"},
"Vanellus miles": {id: 367, genus: "Vanellus", species: "miles", description: "Masked Lapwing"},
"Amytornis barbatus": {id: 368, genus: "Amytornis", species: "barbatus", description: "Grey Grasswren"},
"Amytornis goyderi": {id: 369, genus: "Amytornis", species: "goyderi", description: "Eyrean Grasswren"},
"Amytornis dorotheae": {id: 370, genus: "Amytornis", species: "dorotheae", description: "Carpentarian Grasswren"},
"Amytornis ballarae": {id: 371, genus: "Amytornis", species: "ballarae", description: "Kalkadoon Grasswren"},
"Amytornis purnelli": {id: 372, genus: "Amytornis", species: "purnelli", description: "Dusky Grasswren"},
"Amytornis textilis": {id: 373, genus: "Amytornis", species: "textilis", description: "Thick-billed Grasswren"},
"Amytornis housei": {id: 374, genus: "Amytornis", species: "housei", description: "Black Grasswren"},
"Amytornis striatus": {id: 375, genus: "Amytornis", species: "striatus", description: "Striated Grasswren"},
"Amytornis merrotsyi": {id: 376, genus: "Amytornis", species: "merrotsyi", description: "Short-tailed Grasswren"},
"Amytornis woodwardi": {id: 377, genus: "Amytornis", species: "woodwardi", description: "White-throated Grasswren"},
"Lathamus discolor": {id: 378, genus: "Lathamus", species: "discolor", description: "Swift Parrot"},
"Lophoictinia isura": {id: 379, genus: "Lophoictinia", species: "isura", description: "Square-tailed Kite"},
"Hirundapus caudacutus": {id: 380, genus: "Hirundapus", species: "caudacutus", description: "White-throated Needletail"},
"Scenopoeetes dentirostris": {id: 381, genus: "Scenopoeetes", species: "dentirostris", description: "Tooth-billed Bowerbird"},
"Probosciger aterrimus": {id: 382, genus: "Probosciger", species: "aterrimus", description: "Palm Cockatoo"},
"Gallirallus sylvestris": {id: 383, genus: "Gallirallus", species: "sylvestris", description: "Lord Howe Woodhen"},
"Gallirallus philippensis": {id: 384, genus: "Gallirallus", species: "philippensis", description: "Buff-banded Rail"},
"Colluricincla harmonica": {id: 385, genus: "Colluricincla", species: "harmonica", description: "Grey Shrike-thrush"},
"Colluricincla megarhyncha": {id: 386, genus: "Colluricincla", species: "megarhyncha", description: "Little Shrike-thrush"},
"Colluricincla woodwardi": {id: 387, genus: "Colluricincla", species: "woodwardi", description: "Sandstone Shrike-thrush"},
"Colluricincla boweri": {id: 388, genus: "Colluricincla", species: "boweri", description: "Bower's Shrike-thrush"},
"Cacomantis flabelliformis": {id: 389, genus: "Cacomantis", species: "flabelliformis", description: "Fan-tailed Cuckoo"},
"Cacomantis castaneiventris": {id: 390, genus: "Cacomantis", species: "castaneiventris", description: "Chestnut-breasted Cuckoo"},
"Cacomantis variolosus": {id: 391, genus: "Cacomantis", species: "variolosus", description: "Brush Cuckoo"},
"Cacomantis pallidus": {id: 392, genus: "Cacomantis", species: "pallidus", description: "Pallid Cuckoo"},
"Phoebastria immutabilis": {id: 393, genus: "Phoebastria", species: "immutabilis", description: "Laysan Albatross"},
"Cereopsis novaehollandiae": {id: 394, genus: "Cereopsis", species: "novaehollandiae", description: "Cape Barren Goose"},
"Neophema chrysogaster": {id: 395, genus: "Neophema", species: "chrysogaster", description: "Orange-bellied Parrot"},
"Neophema elegans": {id: 396, genus: "Neophema", species: "elegans", description: "Elegant Parrot"},
"Neophema pulchella": {id: 397, genus: "Neophema", species: "pulchella", description: "Turquoise Parrot"},
"Neophema splendida": {id: 398, genus: "Neophema", species: "splendida", description: "Scarlet-chested Parrot"},
"Neophema petrophila": {id: 399, genus: "Neophema", species: "petrophila", description: "Rock Parrot"},
"Neophema chrysostoma": {id: 400, genus: "Neophema", species: "chrysostoma", description: "Blue-winged Parrot"},
"Tyto tenebricosa": {id: 401, genus: "Tyto", species: "tenebricosa", description: "Sooty Owl"},
"Tyto longimembris": {id: 402, genus: "Tyto", species: "longimembris", description: "Eastern Grass Owl"},
"Tyto novaehollandiae": {id: 403, genus: "Tyto", species: "novaehollandiae", description: "Masked Owl"},
"Tyto javanica": {id: 404, genus: "Tyto", species: "javanica", description: "Eastern Barn Owl"},
"Fulmarus glacialoides": {id: 405, genus: "Fulmarus", species: "glacialoides", description: "Southern Fulmar"},
"Branta canadensis": {id: 406, genus: "Branta", species: "canadensis", description: "Canada Goose"},
"Papasula abbotti": {id: 407, genus: "Papasula", species: "abbotti", description: "Abbott's Booby"},
"Cormobates leucophaea": {id: 408, genus: "Cormobates", species: "leucophaea", description: "White-throated Treecreeper"},
"Chalcophaps indica": {id: 409, genus: "Chalcophaps", species: "indica", description: "Emerald Dove"},
"Microeca fascinans": {id: 410, genus: "Microeca", species: "fascinans", description: "Jacky Winter"},
"Microeca griseoceps": {id: 411, genus: "Microeca", species: "griseoceps", description: "Yellow-legged Flycatcher"},
"Microeca flavigaster": {id: 412, genus: "Microeca", species: "flavigaster", description: "Lemon-bellied Flycatcher"},
"Gallus varius": {id: 413, genus: "Gallus", species: "varius", description: "Green Junglefowl"},
"Gallus gallus": {id: 414, genus: "Gallus", species: "gallus", description: "Red Junglefowl"},
"Corvus tasmanicus": {id: 415, genus: "Corvus", species: "tasmanicus", description: "Forest Raven"},
"Corvus splendens": {id: 416, genus: "Corvus", species: "splendens", description: "House Crow"},
"Corvus coronoides": {id: 417, genus: "Corvus", species: "coronoides", description: "Australian Raven"},
"Corvus mellori": {id: 418, genus: "Corvus", species: "mellori", description: "Little Raven"},
"Corvus bennetti": {id: 419, genus: "Corvus", species: "bennetti", description: "Little Crow"},
"Corvus orru": {id: 420, genus: "Corvus", species: "orru", description: "Torresian Crow"},
"Ninox strenua": {id: 421, genus: "Ninox", species: "strenua", description: "Powerful Owl"},
"Ninox connivens": {id: 422, genus: "Ninox", species: "connivens", description: "Barking Owl"},
"Ninox scutulata": {id: 423, genus: "Ninox", species: "scutulata", description: "Brown Hawk-Owl"},
"Ninox natalis": {id: 424, genus: "Ninox", species: "natalis", description: "Christmas Island Hawk-Owl"},
"Ninox rufa": {id: 425, genus: "Ninox", species: "rufa", description: "Rufous Owl"},
"Ninox novaeseelandiae": {id: 426, genus: "Ninox", species: "novaeseelandiae", description: "Southern Boobook"},
"Gorsachius melanolophus": {id: 427, genus: "Gorsachius", species: "melanolophus", description: "Malayan Night-Heron"},
"Monarcha frater": {id: 428, genus: "Monarcha", species: "frater", description: "Black-winged Monarch"},
"Monarcha cinerascens": {id: 429, genus: "Monarcha", species: "cinerascens", description: "Island Monarch"},
"Monarcha melanopsis": {id: 430, genus: "Monarcha", species: "melanopsis", description: "Black-faced Monarch"},
"Sturnus sturninus": {id: 431, genus: "Sturnus", species: "sturninus", description: "Purple-backed Starling"},
"Sturnus tristis": {id: 432, genus: "Sturnus", species: "tristis", description: "Common Myna"},
"Sturnus roseus": {id: 433, genus: "Sturnus", species: "roseus", description: "Rosy Starling"},
"Sturnus vulgaris": {id: 434, genus: "Sturnus", species: "vulgaris", description: "Common Starling"},
"Amaurornis cinerea": {id: 435, genus: "Amaurornis", species: "cinerea", description: "White-browed Crake"},
"Amaurornis phoenicurus": {id: 436, genus: "Amaurornis", species: "phoenicurus", description: "White-breasted Waterhen"},
"Amaurornis moluccana": {id: 437, genus: "Amaurornis", species: "moluccana", description: "Pale-vented Bush-hen"},
"Geopelia cuneata": {id: 438, genus: "Geopelia", species: "cuneata", description: "Diamond Dove"},
"Geopelia humeralis": {id: 439, genus: "Geopelia", species: "humeralis", description: "Bar-shouldered Dove"},
"Geopelia striata": {id: 440, genus: "Geopelia", species: "striata", description: "Peaceful Dove"},
"Glyciphila melanops": {id: 441, genus: "Glyciphila", species: "melanops", description: "Tawny-crowned Honeyeater"},
"Phonygammus keraudrenii": {id: 442, genus: "Phonygammus", species: "keraudrenii", description: "Trumpet Manucode"},
"Hamirostra melanosternon": {id: 443, genus: "Hamirostra", species: "melanosternon", description: "Black-breasted Buzzard"},
"Eurostopodus mystacalis": {id: 444, genus: "Eurostopodus", species: "mystacalis", description: "White-throated Nightjar"},
"Eurostopodus argus": {id: 445, genus: "Eurostopodus", species: "argus", description: "Spotted Nightjar"},
"Mirafra javanica": {id: 446, genus: "Mirafra", species: "javanica", description: "Horsfield's Bushlark"},
"Nestor productus": {id: 447, genus: "Nestor", species: "productus", description: "Norfolk Island Kaka"},
"Megalurus gramineus": {id: 448, genus: "Megalurus", species: "gramineus", description: "Little Grassbird"},
"Megalurus timoriensis": {id: 449, genus: "Megalurus", species: "timoriensis", description: "Tawny Grassbird"},
"Lalage leucopyga": {id: 450, genus: "Lalage", species: "leucopyga", description: "Long-tailed Triller"},
"Lalage sueurii": {id: 451, genus: "Lalage", species: "sueurii", description: "White-winged Triller"},
"Lalage leucomela": {id: 452, genus: "Lalage", species: "leucomela", description: "Varied Triller"},
"Haliaeetus leucogaster": {id: 453, genus: "Haliaeetus", species: "leucogaster", description: "White-bellied Sea-Eagle"},
"Eurystomus orientalis": {id: 454, genus: "Eurystomus", species: "orientalis", description: "Dollarbird"},
"Ptilinopus iozonus": {id: 455, genus: "Ptilinopus", species: "iozonus", description: "Orange-bellied Fruit-Dove"},
"Ptilinopus superbus": {id: 456, genus: "Ptilinopus", species: "superbus", description: "Superb Fruit-Dove"},
"Ptilinopus regina": {id: 457, genus: "Ptilinopus", species: "regina", description: "Rose-crowned Fruit-Dove"},
"Ptilinopus magnificus": {id: 458, genus: "Ptilinopus", species: "magnificus", description: "Wompoo Fruit-Dove"},
"Ptilinopus cinctus": {id: 459, genus: "Ptilinopus", species: "cinctus", description: "Banded Fruit-Dove"},
"Tryngites subruficollis": {id: 460, genus: "Tryngites", species: "subruficollis", description: "Buff-breasted Sandpiper"},
"Megapodius reinwardt": {id: 461, genus: "Megapodius", species: "reinwardt", description: "Orange-footed Scrubfowl"},
"Cinclosoma castanotum": {id: 462, genus: "Cinclosoma", species: "castanotum", description: "Chestnut Quail-thrush"},
"Cinclosoma cinnamomeum": {id: 463, genus: "Cinclosoma", species: "cinnamomeum", description: "Cinnamon Quail-thrush"},
"Cinclosoma punctatum": {id: 464, genus: "Cinclosoma", species: "punctatum", description: "Spotted Quail-thrush"},
"Cinclosoma castaneothorax": {id: 465, genus: "Cinclosoma", species: "castaneothorax", description: "Chestnut-breasted Quail-thrush"},
"Hemiphaga novaeseelandiae": {id: 466, genus: "Hemiphaga", species: "novaeseelandiae", description: "New Zealand Pigeon"},
"Neochmia modesta": {id: 467, genus: "Neochmia", species: "modesta", description: "Plum-headed Finch"},
"Neochmia temporalis": {id: 468, genus: "Neochmia", species: "temporalis", description: "Red-browed Finch"},
"Neochmia phaeton": {id: 469, genus: "Neochmia", species: "phaeton", description: "Crimson Finch"},
"Neochmia ruficauda": {id: 470, genus: "Neochmia", species: "ruficauda", description: "Star Finch"},
"Poecilodryas superciliosa": {id: 471, genus: "Poecilodryas", species: "superciliosa", description: "White-browed Robin"},
"Poecilodryas cerviniventris": {id: 472, genus: "Poecilodryas", species: "cerviniventris", description: "Buff-sided Robin"},
"Halcyon pileata": {id: 473, genus: "Halcyon", species: "pileata", description: "Black-capped Kingfisher"},
"Coracina maxima": {id: 474, genus: "Coracina", species: "maxima", description: "Ground Cuckoo-shrike"},
"Coracina lineata": {id: 475, genus: "Coracina", species: "lineata", description: "Barred Cuckoo-shrike"},
"Coracina tenuirostris": {id: 476, genus: "Coracina", species: "tenuirostris", description: "Cicadabird"},
"Coracina novaehollandiae": {id: 477, genus: "Coracina", species: "novaehollandiae", description: "Black-faced Cuckoo-shrike"},
"Coracina papuensis": {id: 478, genus: "Coracina", species: "papuensis", description: "White-bellied Cuckoo-shrike"},
"Ardea modesta": {id: 479, genus: "Ardea", species: "modesta", description: "Eastern Great Egret"},
"Ardea sumatrana": {id: 480, genus: "Ardea", species: "sumatrana", description: "Great-billed Heron"},
"Ardea cinerea": {id: 481, genus: "Ardea", species: "cinerea", description: "Grey Heron"},
"Ardea ibis": {id: 482, genus: "Ardea", species: "ibis", description: "Cattle Egret"},
"Ardea intermedia": {id: 483, genus: "Ardea", species: "intermedia", description: "Intermediate Egret"},
"Ardea pacifica": {id: 484, genus: "Ardea", species: "pacifica", description: "White-necked Heron"},
"Turdus poliocephalus": {id: 485, genus: "Turdus", species: "poliocephalus", description: "Island Thrush"},
"Turdus merula": {id: 486, genus: "Turdus", species: "merula", description: "Common Blackbird"},
"Turdus philomelos": {id: 487, genus: "Turdus", species: "philomelos", description: "Song Thrush"},
"Acanthorhynchus tenuirostris": {id: 488, genus: "Acanthorhynchus", species: "tenuirostris", description: "Eastern Spinebill"},
"Acanthorhynchus superciliosus": {id: 489, genus: "Acanthorhynchus", species: "superciliosus", description: "Western Spinebill"},
"Ramsayornis modestus": {id: 490, genus: "Ramsayornis", species: "modestus", description: "Brown-backed Honeyeater"},
"Ramsayornis fasciatus": {id: 491, genus: "Ramsayornis", species: "fasciatus", description: "Bar-breasted Honeyeater"},
"Erythrura trichroa": {id: 492, genus: "Erythrura", species: "trichroa", description: "Blue-faced Parrot-Finch"},
"Erythrura gouldiae": {id: 493, genus: "Erythrura", species: "gouldiae", description: "Gouldian Finch"},
"Grus rubicunda": {id: 494, genus: "Grus", species: "rubicunda", description: "Brolga"},
"Grus antigone": {id: 495, genus: "Grus", species: "antigone", description: "Sarus Crane"},
"Leipoa ocellata": {id: 496, genus: "Leipoa", species: "ocellata", description: "Malleefowl"},
"Caprimulgus affinis": {id: 497, genus: "Caprimulgus", species: "affinis", description: "Savanna Nightjar"},
"Caprimulgus macrurus": {id: 498, genus: "Caprimulgus", species: "macrurus", description: "Large-tailed Nightjar"},
"Caprimulgus indicus": {id: 499, genus: "Caprimulgus", species: "indicus", description: "Grey Nightjar"},
"Peneonanthe pulverulenta": {id: 500, genus: "Peneonanthe", species: "pulverulenta", description: "Mangrove Robin"},
"Hierococcyx sparverioides": {id: 501, genus: "Hierococcyx", species: "sparverioides", description: "Large Hawk-Cuckoo"},
"Barnardius zonarius": {id: 502, genus: "Barnardius", species: "zonarius", description: "Australian Ringneck"},
"Aythya australis": {id: 503, genus: "Aythya", species: "australis", description: "Hardhead"},
"Ephippiorhynchus asiaticus": {id: 504, genus: "Ephippiorhynchus", species: "asiaticus", description: "Black-necked Stork"},
"Esacus magnirostris": {id: 505, genus: "Esacus", species: "magnirostris", description: "Beach Stone-curlew"},
"Taeniopygia bichenovii": {id: 506, genus: "Taeniopygia", species: "bichenovii", description: "Double-barred Finch"},
"Taeniopygia guttata": {id: 507, genus: "Taeniopygia", species: "guttata", description: "Zebra Finch"},
"Eremiornis carteri": {id: 508, genus: "Eremiornis", species: "carteri", description: "Spinifexbird"},
"Phalacrocorax varius": {id: 509, genus: "Phalacrocorax", species: "varius", description: "Pied Cormorant"},
"Phalacrocorax fuscescens": {id: 510, genus: "Phalacrocorax", species: "fuscescens", description: "Black-faced Cormorant"},
"Phalacrocorax sulcirostris": {id: 511, genus: "Phalacrocorax", species: "sulcirostris", description: "Little Black Cormorant"},
"Phalacrocorax carbo": {id: 512, genus: "Phalacrocorax", species: "carbo", description: "Great Cormorant"},
"Porzana fluminea": {id: 513, genus: "Porzana", species: "fluminea", description: "Australian Spotted Crake"},
"Porzana fusca": {id: 514, genus: "Porzana", species: "fusca", description: "Ruddy-breasted Crake"},
"Porzana pusilla": {id: 515, genus: "Porzana", species: "pusilla", description: "Baillon's Crake"},
"Porzana tabuensis": {id: 516, genus: "Porzana", species: "tabuensis", description: "Spotless Crake"},
"Ocyphaps lophotes": {id: 517, genus: "Ocyphaps", species: "lophotes", description: "Crested Pigeon"},
"Petrochelidon nigricans": {id: 518, genus: "Petrochelidon", species: "nigricans", description: "Tree Martin"},
"Petrochelidon ariel": {id: 519, genus: "Petrochelidon", species: "ariel", description: "Fairy Martin"},
"Cheramoeca leucosterna": {id: 520, genus: "Cheramoeca", species: "leucosterna", description: "White-backed Swallow"},
"Stercorarius longicaudus": {id: 521, genus: "Stercorarius", species: "longicaudus", description: "Long-tailed Jaeger"},
"Stercorarius parasiticus": {id: 522, genus: "Stercorarius", species: "parasiticus", description: "Arctic Jaeger"},
"Stercorarius antarcticus": {id: 523, genus: "Stercorarius", species: "antarcticus", description: "Brown Skua"},
"Stercorarius pomarinus": {id: 524, genus: "Stercorarius", species: "pomarinus", description: "Pomarine Jaeger"},
"Stercorarius maccormicki": {id: 525, genus: "Stercorarius", species: "maccormicki", description: "South Polar Skua"},
"Lichenostomus frenatus": {id: 526, genus: "Lichenostomus", species: "frenatus", description: "Bridled Honeyeater"},
"Lichenostomus fasciogularis": {id: 527, genus: "Lichenostomus", species: "fasciogularis", description: "Mangrove Honeyeater"},
"Lichenostomus plumulus": {id: 528, genus: "Lichenostomus", species: "plumulus", description: "Grey-fronted Honeyeater"},
"Lichenostomus chrysops": {id: 529, genus: "Lichenostomus", species: "chrysops", description: "Yellow-faced Honeyeater"},
"Lichenostomus flavicollis": {id: 530, genus: "Lichenostomus", species: "flavicollis", description: "Yellow-throated Honeyeater"},
"Lichenostomus versicolor": {id: 531, genus: "Lichenostomus", species: "versicolor", description: "Varied Honeyeater"},
"Lichenostomus fuscus": {id: 532, genus: "Lichenostomus", species: "fuscus", description: "Fuscous Honeyeater"},
"Lichenostomus leucotis": {id: 533, genus: "Lichenostomus", species: "leucotis", description: "White-eared Honeyeater"},
"Lichenostomus virescens": {id: 534, genus: "Lichenostomus", species: "virescens", description: "Singing Honeyeater"},
"Lichenostomus unicolor": {id: 535, genus: "Lichenostomus", species: "unicolor", description: "White-gaped Honeyeater"},
"Lichenostomus flavescens": {id: 536, genus: "Lichenostomus", species: "flavescens", description: "Yellow-tinted Honeyeater"},
"Lichenostomus melanops": {id: 537, genus: "Lichenostomus", species: "melanops", description: "Yellow-tufted Honeyeater"},
"Lichenostomus ornatus": {id: 538, genus: "Lichenostomus", species: "ornatus", description: "Yellow-plumed Honeyeater"},
"Lichenostomus penicillatus": {id: 539, genus: "Lichenostomus", species: "penicillatus", description: "White-plumed Honeyeater"},
"Lichenostomus keartlandi": {id: 540, genus: "Lichenostomus", species: "keartlandi", description: "Grey-headed Honeyeater"},
"Lichenostomus cratitius": {id: 541, genus: "Lichenostomus", species: "cratitius", description: "Purple-gaped Honeyeater"},
"Lichenostomus hindwoodi": {id: 542, genus: "Lichenostomus", species: "hindwoodi", description: "Eungella Honeyeater"},
"Lichenostomus flavus": {id: 543, genus: "Lichenostomus", species: "flavus", description: "Yellow Honeyeater"},
"Leucosarcia picata": {id: 544, genus: "Leucosarcia", species: "picata", description: "Wonga Pigeon"},
"Elseyornis melanops": {id: 545, genus: "Elseyornis", species: "melanops", description: "Black-fronted Dotterel"},
"Casuarius casuarius": {id: 546, genus: "Casuarius", species: "casuarius", description: "Southern Cassowary"},
"Accipiter fasciatus": {id: 547, genus: "Accipiter", species: "fasciatus", description: "Brown Goshawk"},
"Accipiter hiogaster": {id: 548, genus: "Accipiter", species: "hiogaster", description: "Variable Goshawk"},
"Accipiter novaehollandiae": {id: 549, genus: "Accipiter", species: "novaehollandiae", description: "Grey Goshawk"},
"Accipiter cirrocephalus": {id: 550, genus: "Accipiter", species: "cirrocephalus", description: "Collared Sparrowhawk"},
"Bulweria fallax": {id: 551, genus: "Bulweria", species: "fallax", description: "Jouanin's Petrel"},
"Bulweria bulwerii": {id: 552, genus: "Bulweria", species: "bulwerii", description: "Bulwer's Petrel"},
"Puffinus newelli": {id: 553, genus: "Puffinus", species: "newelli", description: "Newell's Shearwater"},
"Puffinus puffinus": {id: 554, genus: "Puffinus", species: "puffinus", description: "Manx Shearwater"},
"Puffinus lherminieri": {id: 555, genus: "Puffinus", species: "lherminieri", description: "Audubon's Shearwater"},
"Puffinus gavia": {id: 556, genus: "Puffinus", species: "gavia", description: "Fluttering Shearwater"},
"Puffinus assimilis": {id: 557, genus: "Puffinus", species: "assimilis", description: "Little Shearwater"},
"Puffinus huttoni": {id: 558, genus: "Puffinus", species: "huttoni", description: "Hutton's Shearwater"},
"Passer montanus": {id: 559, genus: "Passer", species: "montanus", description: "Eurasian Tree Sparrow"},
"Passer domesticus": {id: 560, genus: "Passer", species: "domesticus", description: "House Sparrow"},
"Ardeotis australis": {id: 561, genus: "Ardeotis", species: "australis", description: "Australian Bustard"},
"Aegotheles cristatus": {id: 562, genus: "Aegotheles", species: "cristatus", description: "Australian Owlet-nightjar"},
"Erythrotriorchis radiatus": {id: 563, genus: "Erythrotriorchis", species: "radiatus", description: "Red Goshawk"},
"Pygoscelis papua": {id: 564, genus: "Pygoscelis", species: "papua", description: "Gentoo Penguin"},
"Pygoscelis antarcticus": {id: 565, genus: "Pygoscelis", species: "antarcticus", description: "Chinstrap Penguin"},
"Pygoscelis adeliae": {id: 566, genus: "Pygoscelis", species: "adeliae", description: "Adelie Penguin"},
"Phaps histrionica": {id: 567, genus: "Phaps", species: "histrionica", description: "Flock Bronzewing"},
"Phaps chalcoptera": {id: 568, genus: "Phaps", species: "chalcoptera", description: "Common Bronzewing"},
"Phaps elegans": {id: 569, genus: "Phaps", species: "elegans", description: "Brush Bronzewing"},
"Centropus bengalensis": {id: 570, genus: "Centropus", species: "bengalensis", description: "Lesser Coucal"},
"Centropus phasianinus": {id: 571, genus: "Centropus", species: "phasianinus", description: "Pheasant Coucal"},
"Anseranas semipalmata": {id: 572, genus: "Anseranas", species: "semipalmata", description: "Magpie Goose"},
"Pavo cristatus": {id: 573, genus: "Pavo", species: "cristatus", description: "Indian Peafowl"},
"Pandion cristatus": {id: 574, genus: "Pandion", species: "cristatus", description: "Eastern Osprey"},
"Pelagodroma marina": {id: 575, genus: "Pelagodroma", species: "marina", description: "White-faced Storm-Petrel"},
"Anous minutus": {id: 576, genus: "Anous", species: "minutus", description: "Black Noddy"},
"Anous tenuirostris": {id: 577, genus: "Anous", species: "tenuirostris", description: "Lesser Noddy"},
"Anous stolidus": {id: 578, genus: "Anous", species: "stolidus", description: "Common Noddy"},
"Botaurus poiciloptilus": {id: 579, genus: "Botaurus", species: "poiciloptilus", description: "Australasian Bittern"},
"Oriolus sagittatus": {id: 580, genus: "Oriolus", species: "sagittatus", description: "Olive-backed Oriole"},
"Oriolus flavocinctus": {id: 581, genus: "Oriolus", species: "flavocinctus", description: "Yellow Oriole"},
"Circus assimilis": {id: 582, genus: "Circus", species: "assimilis", description: "Spotted Harrier"},
"Circus approximans": {id: 583, genus: "Circus", species: "approximans", description: "Swamp Harrier"},
"Turnix varius": {id: 584, genus: "Turnix", species: "varius", description: "Painted Button-quail"},
"Turnix olivii": {id: 585, genus: "Turnix", species: "olivii", description: "Buff-breasted Button-quail"},
"Turnix melanogaster": {id: 586, genus: "Turnix", species: "melanogaster", description: "Black-breasted Button-quail"},
"Turnix velox": {id: 587, genus: "Turnix", species: "velox", description: "Little Button-quail"},
"Turnix pyrrhothorax": {id: 588, genus: "Turnix", species: "pyrrhothorax", description: "Red-chested Button-quail"},
"Turnix castanotus": {id: 589, genus: "Turnix", species: "castanotus", description: "Chestnut-backed Button-quail"},
"Turnix maculosus": {id: 590, genus: "Turnix", species: "maculosus", description: "Red-backed Button-quail"},
"Gerygone tenebrosa": {id: 591, genus: "Gerygone", species: "tenebrosa", description: "Dusky Gerygone"},
"Gerygone fusca": {id: 592, genus: "Gerygone", species: "fusca", description: "Western Gerygone"},
"Gerygone magnirostris": {id: 593, genus: "Gerygone", species: "magnirostris", description: "Large-billed Gerygone"},
"Gerygone levigaster": {id: 594, genus: "Gerygone", species: "levigaster", description: "Mangrove Gerygone"},
"Gerygone mouki": {id: 595, genus: "Gerygone", species: "mouki", description: "Brown Gerygone"},
"Gerygone modesta": {id: 596, genus: "Gerygone", species: "modesta", description: "Norfolk Island Gerygone"},
"Gerygone albogularis": {id: 597, genus: "Gerygone", species: "albogularis", description: "White-throated Gerygone"},
"Gerygone insularis": {id: 598, genus: "Gerygone", species: "insularis", description: "Lord Howe Gerygone"},
"Gerygone chloronota": {id: 599, genus: "Gerygone", species: "chloronota", description: "Green-backed Gerygone"},
"Gerygone palpebrosa": {id: 600, genus: "Gerygone", species: "palpebrosa", description: "Fairy Gerygone"},
"Stiltia isabella": {id: 601, genus: "Stiltia", species: "isabella", description: "Australian Pratincole"},
"Cincloramphus mathewsi": {id: 602, genus: "Cincloramphus", species: "mathewsi", description: "Rufous Songlark"},
"Cincloramphus cruralis": {id: 603, genus: "Cincloramphus", species: "cruralis", description: "Brown Songlark"},
"Chalcites lucidus": {id: 604, genus: "Chalcites", species: "lucidus", description: "Shining Bronze-Cuckoo"},
"Chalcites minutillus": {id: 605, genus: "Chalcites", species: "minutillus", description: "Little Bronze-Cuckoo"},
"Chalcites basalis": {id: 606, genus: "Chalcites", species: "basalis", description: "Horsfield's Bronze-Cuckoo"},
"Chalcites osculans": {id: 607, genus: "Chalcites", species: "osculans", description: "Black-eared Cuckoo"},
"Xema sabini": {id: 608, genus: "Xema", species: "sabini", description: "Sabine's Gull"},
"Neopsephotus bourkii": {id: 609, genus: "Neopsephotus", species: "bourkii", description: "Bourke's Parrot"},
"Anthochaera lunulata": {id: 610, genus: "Anthochaera", species: "lunulata", description: "Western Wattlebird"},
"Anthochaera paradoxa": {id: 611, genus: "Anthochaera", species: "paradoxa", description: "Yellow Wattlebird"},
"Anthochaera chrysoptera": {id: 612, genus: "Anthochaera", species: "chrysoptera", description: "Little Wattlebird"},
"Anthochaera carunculata": {id: 613, genus: "Anthochaera", species: "carunculata", description: "Red Wattlebird"},
"Anthochaera phrygia": {id: 614, genus: "Anthochaera", species: "phrygia", description: "Regent Honeyeater"},
"Gallinago stenura": {id: 615, genus: "Gallinago", species: "stenura", description: "Pin-tailed Snipe"},
"Gallinago megala": {id: 616, genus: "Gallinago", species: "megala", description: "Swinhoe's Snipe"},
"Gallinago hardwickii": {id: 617, genus: "Gallinago", species: "hardwickii", description: "Latham's Snipe"},
"Hydrobates tristrami": {id: 618, genus: "Hydrobates", species: "tristrami", description: "Tristram's Storm-Petrel"},
"Hydrobates matsudairae": {id: 619, genus: "Hydrobates", species: "matsudairae", description: "Matsudaira's Storm-Petrel"},
"Hydrobates leucorhoa": {id: 620, genus: "Hydrobates", species: "leucorhoa", description: "Leach's Storm-Petrel"},
"Hydrobates monorhis": {id: 621, genus: "Hydrobates", species: "monorhis", description: "Swinhoe's Storm-Petrel"},
"Leucophaeus atricilla": {id: 622, genus: "Leucophaeus", species: "atricilla", description: "Laughing Gull"},
"Leucophaeus pipixcan": {id: 623, genus: "Leucophaeus", species: "pipixcan", description: "Franklin's Gull"},
"Atrichornis clamosus": {id: 624, genus: "Atrichornis", species: "clamosus", description: "Noisy Scrub-bird"},
"Atrichornis rufescens": {id: 625, genus: "Atrichornis", species: "rufescens", description: "Rufous Scrub-bird"},
"Sugomel niger": {id: 626, genus: "Sugomel", species: "niger", description: "Black Honeyeater"},
"Hydrophasianus chirurgus": {id: 627, genus: "Hydrophasianus", species: "chirurgus", description: "Pheasant-tailed Jacana"},
"Alcedo atthis": {id: 628, genus: "Alcedo", species: "atthis", description: "Common Kingfisher"},
"Melopsittacus undulatus": {id: 629, genus: "Melopsittacus", species: "undulatus", description: "Budgerigar"},
"Orthonyx spaldingii": {id: 630, genus: "Orthonyx", species: "spaldingii", description: "Chowchilla"},
"Orthonyx temminckii": {id: 631, genus: "Orthonyx", species: "temminckii", description: "Australian Logrunner"},
"Myiagra ruficollis": {id: 632, genus: "Myiagra", species: "ruficollis", description: "Broad-billed Flycatcher"},
"Myiagra rubecula": {id: 633, genus: "Myiagra", species: "rubecula", description: "Leaden Flycatcher"},
"Myiagra alecto": {id: 634, genus: "Myiagra", species: "alecto", description: "Shining Flycatcher"},
"Myiagra cyanoleuca": {id: 635, genus: "Myiagra", species: "cyanoleuca", description: "Satin Flycatcher"},
"Myiagra inquieta": {id: 636, genus: "Myiagra", species: "inquieta", description: "Restless Flycatcher"},
"Fringilla coelebs": {id: 637, genus: "Fringilla", species: "coelebs", description: "Common Chaffinch"},
"Sterna hirundo": {id: 638, genus: "Sterna", species: "hirundo", description: "Common Tern"},
"Sterna vittata": {id: 639, genus: "Sterna", species: "vittata", description: "Antarctic Tern"},
"Sterna sumatrana": {id: 640, genus: "Sterna", species: "sumatrana", description: "Black-naped Tern"},
"Sterna dougallii": {id: 641, genus: "Sterna", species: "dougallii", description: "Roseate Tern"},
"Sterna paradisaea": {id: 642, genus: "Sterna", species: "paradisaea", description: "Arctic Tern"},
"Sterna striata": {id: 643, genus: "Sterna", species: "striata", description: "White-fronted Tern"},
"Larus crassirostris": {id: 644, genus: "Larus", species: "crassirostris", description: "Black-tailed Gull"},
"Larus dominicanus": {id: 645, genus: "Larus", species: "dominicanus", description: "Kelp Gull"},
"Larus canus": {id: 646, genus: "Larus", species: "canus", description: "Mew Gull"},
"Larus fuscus": {id: 647, genus: "Larus", species: "fuscus", description: "Lesser Black-backed Gull"},
"Larus pacificus": {id: 648, genus: "Larus", species: "pacificus", description: "Pacific Gull"},
"Chlidonias leucopterus": {id: 649, genus: "Chlidonias", species: "leucopterus", description: "White-winged Black Tern"},
"Chlidonias niger": {id: 650, genus: "Chlidonias", species: "niger", description: "Black Tern"},
"Chlidonias hybrida": {id: 651, genus: "Chlidonias", species: "hybrida", description: "Whiskered Tern"},
"Glossopsitta porphyrocephala": {id: 652, genus: "Glossopsitta", species: "porphyrocephala", description: "Purple-crowned Lorikeet"},
"Glossopsitta pusilla": {id: 653, genus: "Glossopsitta", species: "pusilla", description: "Little Lorikeet"},
"Glossopsitta concinna": {id: 654, genus: "Glossopsitta", species: "concinna", description: "Musk Lorikeet"},
"Phylidonyris pyrrhopterus": {id: 655, genus: "Phylidonyris", species: "pyrrhopterus", description: "Crescent Honeyeater"},
"Phylidonyris niger": {id: 656, genus: "Phylidonyris", species: "niger", description: "White-cheeked Honeyeater"},
"Phylidonyris novaehollandiae": {id: 657, genus: "Phylidonyris", species: "novaehollandiae", description: "New Holland Honeyeater"},
"Tringa stagnatilis": {id: 658, genus: "Tringa", species: "stagnatilis", description: "Marsh Sandpiper"},
"Tringa glareola": {id: 659, genus: "Tringa", species: "glareola", description: "Wood Sandpiper"},
"Tringa flavipes": {id: 660, genus: "Tringa", species: "flavipes", description: "Lesser Yellowlegs"},
"Tringa incana": {id: 661, genus: "Tringa", species: "incana", description: "Wandering Tattler"},
"Tringa erythropus": {id: 662, genus: "Tringa", species: "erythropus", description: "Spotted Redshank"},
"Tringa ochropus": {id: 663, genus: "Tringa", species: "ochropus", description: "Green Sandpiper"},
"Tringa totanus": {id: 664, genus: "Tringa", species: "totanus", description: "Common Redshank"},
"Tringa guttifer": {id: 665, genus: "Tringa", species: "guttifer", description: "Nordmann's Greenshank"},
"Tringa nebularia": {id: 666, genus: "Tringa", species: "nebularia", description: "Common Greenshank"},
"Tringa brevipes": {id: 667, genus: "Tringa", species: "brevipes", description: "Grey-tailed Tattler"},
"Aprosmictus erythropterus": {id: 668, genus: "Aprosmictus", species: "erythropterus", description: "Red-winged Parrot"},
"Machaerirhynchus flaviventer": {id: 669, genus: "Machaerirhynchus", species: "flaviventer", description: "Yellow-breasted Boatbill"},
"Gallicrex cinerea": {id: 670, genus: "Gallicrex", species: "cinerea", description: "Watercock"},
"Limosa haemastica": {id: 671, genus: "Limosa", species: "haemastica", description: "Hudsonian Godwit"},
"Limosa lapponica": {id: 672, genus: "Limosa", species: "lapponica", description: "Bar-tailed Godwit"},
"Limosa limosa": {id: 673, genus: "Limosa", species: "limosa", description: "Black-tailed Godwit"},
"Chloris chloris": {id: 674, genus: "Chloris", species: "chloris", description: "Common Greenfinch"},
"Gallinula tenebrosa": {id: 675, genus: "Gallinula", species: "tenebrosa", description: "Dusky Moorhen"},
"Onychoprion fuscata": {id: 676, genus: "Onychoprion", species: "fuscata", description: "Sooty Tern"},
"Onychoprion anaethetus": {id: 677, genus: "Onychoprion", species: "anaethetus", description: "Bridled Tern"},
"Psephotus varius": {id: 678, genus: "Psephotus", species: "varius", description: "Mulga Parrot"},
"Psephotus dissimilis": {id: 679, genus: "Psephotus", species: "dissimilis", description: "Hooded Parrot"},
"Psephotus haematonotus": {id: 680, genus: "Psephotus", species: "haematonotus", description: "Red-rumped Parrot"},
"Psephotus chrysopterygius": {id: 681, genus: "Psephotus", species: "chrysopterygius", description: "Golden-shouldered Parrot"},
"Psephotus pulcherrimus": {id: 682, genus: "Psephotus", species: "pulcherrimus", description: "Paradise Parrot"},
"Grantiella picta": {id: 683, genus: "Grantiella", species: "picta", description: "Painted Honeyeater"},
"Nycticorax nycticorax": {id: 684, genus: "Nycticorax", species: "nycticorax", description: "Black-crowned Night-Heron"},
"Nycticorax caledonicus": {id: 685, genus: "Nycticorax", species: "caledonicus", description: "Nankeen Night-Heron"},
"Oreoscopus gutturalis": {id: 686, genus: "Oreoscopus", species: "gutturalis", description: "Fernwren"},
"Biziura lobata": {id: 687, genus: "Biziura", species: "lobata", description: "Musk Duck"},
"Trichoglossus haematodus": {id: 688, genus: "Trichoglossus", species: "haematodus", description: "Rainbow Lorikeet"},
"Trichoglossus chlorolepidotus": {id: 689, genus: "Trichoglossus", species: "chlorolepidotus", description: "Scaly-breasted Lorikeet"},
"Numida meleagris": {id: 690, genus: "Numida", species: "meleagris", description: "Helmeted Guineafowl"},
"Merops ornatus": {id: 691, genus: "Merops", species: "ornatus", description: "Rainbow Bee-eater"},
"Grallina cyanoleuca": {id: 692, genus: "Grallina", species: "cyanoleuca", description: "Magpie-lark"},
"Aerodramus terrareginae": {id: 693, genus: "Aerodramus", species: "terrareginae", description: "Australian Swiftlet"},
"Aerodramus vanikorensis": {id: 694, genus: "Aerodramus", species: "vanikorensis", description: "Uniform Swiftlet"},
"Calyptorhynchus baudinii": {id: 695, genus: "Calyptorhynchus", species: "baudinii", description: "Baudin's Black-Cockatoo"},
"Calyptorhynchus funereus": {id: 696, genus: "Calyptorhynchus", species: "funereus", description: "Yellow-tailed Black-Cockatoo"},
"Calyptorhynchus lathami": {id: 697, genus: "Calyptorhynchus", species: "lathami", description: "Glossy Black-Cockatoo"},
"Calyptorhynchus latirostris": {id: 698, genus: "Calyptorhynchus", species: "latirostris", description: "Carnaby's Black-Cockatoo"},
"Calyptorhynchus banksii": {id: 699, genus: "Calyptorhynchus", species: "banksii", description: "Red-tailed Black-Cockatoo"},
"Pluvialis fulva": {id: 700, genus: "Pluvialis", species: "fulva", description: "Pacific Golden Plover"},
"Pluvialis dominicus": {id: 701, genus: "Pluvialis", species: "dominicus", description: "American Golden Plover"},
"Pluvialis squatarola": {id: 702, genus: "Pluvialis", species: "squatarola", description: "Grey Plover"},
"Thinornis rubricollis": {id: 703, genus: "Thinornis", species: "rubricollis", description: "Hooded Plover"},
"Bubo ketupu": {id: 704, genus: "Bubo", species: "ketupu", description: "Buffy Fish-Owl"},
"Aquila gurneyi": {id: 705, genus: "Aquila", species: "gurneyi", description: "Gurney's Eagle"},
"Aquila audax": {id: 706, genus: "Aquila", species: "audax", description: "Wedge-tailed Eagle"},
"Plegadis falcinellus": {id: 707, genus: "Plegadis", species: "falcinellus", description: "Glossy Ibis"},
"Pagodroma nivea": {id: 708, genus: "Pagodroma", species: "nivea", description: "Snow Petrel"},
"Xenus cinereus": {id: 709, genus: "Xenus", species: "cinereus", description: "Terek Sandpiper"},
"Ptiloris magnificus": {id: 710, genus: "Ptiloris", species: "magnificus", description: "Magnificent Riflebird"},
"Ptiloris paradiseus": {id: 711, genus: "Ptiloris", species: "paradiseus", description: "Paradise Riflebird"},
"Ptiloris victoriae": {id: 712, genus: "Ptiloris", species: "victoriae", description: "Victoria's Riflebird"},
"Alisterus scapularis": {id: 713, genus: "Alisterus", species: "scapularis", description: "Australian King-Parrot"},
"Falcunculus frontatus": {id: 714, genus: "Falcunculus", species: "frontatus", description: "Crested Shrike-tit"},
"Platalea flavipes": {id: 715, genus: "Platalea", species: "flavipes", description: "Yellow-billed Spoonbill"},
"Platalea regia": {id: 716, genus: "Platalea", species: "regia", description: "Royal Spoonbill"},
"Podargus ocellatus": {id: 717, genus: "Podargus", species: "ocellatus", description: "Marbled Frogmouth"},
"Podargus papuensis": {id: 718, genus: "Podargus", species: "papuensis", description: "Papuan Frogmouth"},
"Podargus strigoides": {id: 719, genus: "Podargus", species: "strigoides", description: "Tawny Frogmouth"},
"Artamus cyanopterus": {id: 720, genus: "Artamus", species: "cyanopterus", description: "Dusky Woodswallow"},
"Artamus superciliosus": {id: 721, genus: "Artamus", species: "superciliosus", description: "White-browed Woodswallow"},
"Artamus minor": {id: 722, genus: "Artamus", species: "minor", description: "Little Woodswallow"},
"Artamus cinereus": {id: 723, genus: "Artamus", species: "cinereus", description: "Black-faced Woodswallow"},
"Artamus personatus": {id: 724, genus: "Artamus", species: "personatus", description: "Masked Woodswallow"},
"Artamus leucorynchus": {id: 725, genus: "Artamus", species: "leucorynchus", description: "White-breasted Woodswallow"},
"Emberiza citrinella": {id: 726, genus: "Emberiza", species: "citrinella", description: "Yellowhammer"},
"Oenanthe isabellina": {id: 727, genus: "Oenanthe", species: "isabellina", description: "Isabelline Wheatear"},
"Pardalotus rubricatus": {id: 728, genus: "Pardalotus", species: "rubricatus", description: "Red-browed Pardalote"},
"Pardalotus punctatus": {id: 729, genus: "Pardalotus", species: "punctatus", description: "Spotted Pardalote"},
"Pardalotus striatus": {id: 730, genus: "Pardalotus", species: "striatus", description: "Striated Pardalote"},
"Pardalotus quadragintus": {id: 731, genus: "Pardalotus", species: "quadragintus", description: "Forty-spotted Pardalote"},
"Urodynamys taitensis": {id: 732, genus: "Urodynamys", species: "taitensis", description: "Long-tailed Cuckoo"},
"Ficedula narcissina": {id: 733, genus: "Ficedula", species: "narcissina", description: "Narcissus Flycatcher"},
"Pezoporus wallicus": {id: 734, genus: "Pezoporus", species: "wallicus", description: "Ground Parrot"},
"Pezoporus occidentalis": {id: 735, genus: "Pezoporus", species: "occidentalis", description: "Night Parrot"},
"Platycercus icterotis": {id: 736, genus: "Platycercus", species: "icterotis", description: "Western Rosella"},
"Platycercus elegans": {id: 737, genus: "Platycercus", species: "elegans", description: "Crimson Rosella"},
"Platycercus eximius": {id: 738, genus: "Platycercus", species: "eximius", description: "Eastern Rosella"},
"Platycercus caledonicus": {id: 739, genus: "Platycercus", species: "caledonicus", description: "Green Rosella"},
"Platycercus adscitus": {id: 740, genus: "Platycercus", species: "adscitus", description: "Pale-headed Rosella"},
"Platycercus venustus": {id: 741, genus: "Platycercus", species: "venustus", description: "Northern Rosella"},
"Pomatostomus ruficeps": {id: 742, genus: "Pomatostomus", species: "ruficeps", description: "Chestnut-crowned Babbler"},
"Pomatostomus temporalis": {id: 743, genus: "Pomatostomus", species: "temporalis", description: "Grey-crowned Babbler"},
"Pomatostomus halli": {id: 744, genus: "Pomatostomus", species: "halli", description: "Hall's Babbler"},
"Pomatostomus superciliosus": {id: 745, genus: "Pomatostomus", species: "superciliosus", description: "White-browed Babbler"},
"Manorina melanocephala": {id: 746, genus: "Manorina", species: "melanocephala", description: "Noisy Miner"},
"Manorina melanophrys": {id: 747, genus: "Manorina", species: "melanophrys", description: "Bell Miner"},
"Manorina flavigula": {id: 748, genus: "Manorina", species: "flavigula", description: "Yellow-throated Miner"},
"Manorina melanotis": {id: 749, genus: "Manorina", species: "melanotis", description: "Black-eared Miner"},
"Apus affinis": {id: 750, genus: "Apus", species: "affinis", description: "House Swift"},
"Apus pacificus": {id: 751, genus: "Apus", species: "pacificus", description: "Fork-tailed Swift"},
"Purnella albifrons": {id: 752, genus: "Purnella", species: "albifrons", description: "White-fronted Honeyeater"},
"Menura alberti": {id: 753, genus: "Menura", species: "alberti", description: "Albert's Lyrebird"},
"Menura novaehollandiae": {id: 754, genus: "Menura", species: "novaehollandiae", description: "Superb Lyrebird"},
"Anas superciliosa": {id: 755, genus: "Anas", species: "superciliosa", description: "Pacific Black Duck"},
"Anas querquedula": {id: 756, genus: "Anas", species: "querquedula", description: "Garganey"},
"Anas clypeata": {id: 757, genus: "Anas", species: "clypeata", description: "Northern Shoveler"},
"Anas eatoni": {id: 758, genus: "Anas", species: "eatoni", description: "Kerguelen Pintail"},
"Anas platyrhynchos": {id: 759, genus: "Anas", species: "platyrhynchos", description: "Northern Mallard"},
"Anas gracilis": {id: 760, genus: "Anas", species: "gracilis", description: "Grey Teal"},
"Anas rhynchotis": {id: 761, genus: "Anas", species: "rhynchotis", description: "Australasian Shoveler"},
"Anas acuta": {id: 762, genus: "Anas", species: "acuta", description: "Northern Pintail"},
"Anas castanea": {id: 763, genus: "Anas", species: "castanea", description: "Chestnut Teal"},
"Anthus gustavi": {id: 764, genus: "Anthus", species: "gustavi", description: "Pechora Pipit"},
"Anthus cervinus": {id: 765, genus: "Anthus", species: "cervinus", description: "Red-throated Pipit"},
"Anthus novaeseelandiae": {id: 766, genus: "Anthus", species: "novaeseelandiae", description: "Australasian Pipit"},
"Acanthagenys rufogularis": {id: 767, genus: "Acanthagenys", species: "rufogularis", description: "Spiny-cheeked Honeyeater"},
"Elanus scriptus": {id: 768, genus: "Elanus", species: "scriptus", description: "Letter-winged Kite"},
"Elanus axillaris": {id: 769, genus: "Elanus", species: "axillaris", description: "Black-shouldered Kite"},
"Callipepla californica": {id: 770, genus: "Callipepla", species: "californica", description: "California Quail"},
"Callocephalon fimbriatum": {id: 771, genus: "Callocephalon", species: "fimbriatum", description: "Gang-gang Cockatoo"},
"Trichodere cockerelli": {id: 772, genus: "Trichodere", species: "cockerelli", description: "White-streaked Honeyeater"},
"Fregetta grallaria": {id: 773, genus: "Fregetta", species: "grallaria", description: "White-bellied Storm-Petrel"},
"Fregetta tropica": {id: 774, genus: "Fregetta", species: "tropica", description: "Black-bellied Storm-Petrel"},
"Anhinga novaehollandiae": {id: 775, genus: "Anhinga", species: "novaehollandiae", description: "Australasian Darter"},
"Sphecotheres vieilloti": {id: 776, genus: "Sphecotheres", species: "vieilloti", description: "Australasian Figbird"},
"Calamanthus fuliginosus": {id: 777, genus: "Calamanthus", species: "fuliginosus", description: "Striated Fieldwren"},
"Calamanthus pyrrhopygia": {id: 778, genus: "Calamanthus", species: "pyrrhopygia", description: "Chestnut-rumped Heathwren"},
"Calamanthus cautus": {id: 779, genus: "Calamanthus", species: "cautus", description: "Shy Heathwren"},
"Calamanthus campestris": {id: 780, genus: "Calamanthus", species: "campestris", description: "Rufous Fieldwren"},
"Monticola solitarius": {id: 781, genus: "Monticola", species: "solitarius", description: "Blue Rock Thrush"},
"Glycichaera fallax": {id: 782, genus: "Glycichaera", species: "fallax", description: "Green-backed Honeyeater"},
"Oceanites oceanicus": {id: 783, genus: "Oceanites", species: "oceanicus", description: "Wilson's Storm-Petrel"},
"Northiella haematogaster": {id: 784, genus: "Northiella", species: "haematogaster", description: "Blue Bonnet"},
"Phoenicopterus ruber": {id: 785, genus: "Phoenicopterus", species: "ruber", description: "Greater Flamingo"},
"Carduelis carduelis": {id: 786, genus: "Carduelis", species: "carduelis", description: "European Goldfinch"},
"Arenaria interpres": {id: 787, genus: "Arenaria", species: "interpres", description: "Ruddy Turnstone"},
"Lichmera indistincta": {id: 788, genus: "Lichmera", species: "indistincta", description: "Brown Honeyeater"},
"Cyanoramphus cookii": {id: 789, genus: "Cyanoramphus", species: "cookii", description: "Tasman Parakeet"},
"Cyanoramphus novaezelandiae": {id: 790, genus: "Cyanoramphus", species: "novaezelandiae", description: "Red-fronted Parakeet"},
"Streptopelia senegalensis": {id: 791, genus: "Streptopelia", species: "senegalensis", description: "Laughing Dove"},
"Streptopelia roseogrisea": {id: 792, genus: "Streptopelia", species: "roseogrisea", description: "Barbary Dove"},
"Streptopelia chinensis": {id: 793, genus: "Streptopelia", species: "chinensis", description: "Spotted Dove"},
"Streptopelia tranquebarica": {id: 794, genus: "Streptopelia", species: "tranquebarica", description: "Red Collared Dove"},
"Stipiturus mallee": {id: 795, genus: "Stipiturus", species: "mallee", description: "Mallee Emu-wren"},
"Stipiturus ruficeps": {id: 796, genus: "Stipiturus", species: "ruficeps", description: "Rufous-crowned Emu-wren"},
"Stipiturus malachurus": {id: 797, genus: "Stipiturus", species: "malachurus", description: "Southern Emu-wren"},
"Nettapus pulchellus": {id: 798, genus: "Nettapus", species: "pulchellus", description: "Green Pygmy-goose"},
"Nettapus coromandelianus": {id: 799, genus: "Nettapus", species: "coromandelianus", description: "Cotton Pygmy-goose"},
"Fulica atra": {id: 800, genus: "Fulica", species: "atra", description: "Eurasian Coot"},
"Lewinia pectoralis": {id: 801, genus: "Lewinia", species: "pectoralis", description: "Lewin's Rail"},
"Sericulus chrysocephalus": {id: 802, genus: "Sericulus", species: "chrysocephalus", description: "Regent Bowerbird"},
"Melanodryas vittata": {id: 803, genus: "Melanodryas", species: "vittata", description: "Dusky Robin"},
"Melanodryas cucullata": {id: 804, genus: "Melanodryas", species: "cucullata", description: "Hooded Robin"},
"Acrocephalus australis": {id: 805, genus: "Acrocephalus", species: "australis", description: "Australian Reed-Warbler"},
"Acrocephalus orientalis": {id: 806, genus: "Acrocephalus", species: "orientalis", description: "Oriental Reed-Warbler"},
"Steganopus tricolor": {id: 807, genus: "Steganopus", species: "tricolor", description: "Wilson's Phalarope"},
"Eolophus roseicapillus": {id: 808, genus: "Eolophus", species: "roseicapillus", description: "Galah"},
"Cuculus optatus": {id: 809, genus: "Cuculus", species: "optatus", description: "Oriental Cuckoo"},
"Gallicolumba norfolciensis": {id: 810, genus: "Gallicolumba", species: "norfolciensis", description: "Norfolk Island Ground-Dove"},
"Oreoica gutturalis": {id: 811, genus: "Oreoica", species: "gutturalis", description: "Crested Bellbird"},
"Recurvirostra novaehollandiae": {id: 812, genus: "Recurvirostra", species: "novaehollandiae", description: "Red-necked Avocet"},
"Lonchura pallida": {id: 813, genus: "Lonchura", species: "pallida", description: "Pale-headed Munia"},
"Lonchura punctulata": {id: 814, genus: "Lonchura", species: "punctulata", description: "Nutmeg Mannikin"},
"Lonchura flaviprymna": {id: 815, genus: "Lonchura", species: "flaviprymna", description: "Yellow-rumped Mannikin"},
"Lonchura castaneothorax": {id: 816, genus: "Lonchura", species: "castaneothorax", description: "Chestnut-breasted Mannikin"},
"Lonchura oryzivora": {id: 817, genus: "Lonchura", species: "oryzivora", description: "Java Sparrow"},
"Numenius minutus": {id: 818, genus: "Numenius", species: "minutus", description: "Little Curlew"},
"Numenius phaeopus": {id: 819, genus: "Numenius", species: "phaeopus", description: "Whimbrel"},
"Numenius madagascariensis": {id: 820, genus: "Numenius", species: "madagascariensis", description: "Eastern Curlew"},
"Eudynamys scolopaceus": {id: 821, genus: "Eudynamys", species: "scolopaceus", description: "Asian Koel"},
"Eudynamys orientalis": {id: 822, genus: "Eudynamys", species: "orientalis", description: "Eastern Koel"},
"Meleagris gallopavo": {id: 823, genus: "Meleagris", species: "gallopavo", description: "Wild Turkey"},
"Malurus melanocephalus": {id: 824, genus: "Malurus", species: "melanocephalus", description: "Red-backed Fairy-wren"},
"Malurus splendens": {id: 825, genus: "Malurus", species: "splendens", description: "Splendid Fairy-wren"},
"Malurus elegans": {id: 826, genus: "Malurus", species: "elegans", description: "Red-winged Fairy-wren"},
"Malurus pulcherrimus": {id: 827, genus: "Malurus", species: "pulcherrimus", description: "Blue-breasted Fairy-wren"},
"Malurus lamberti": {id: 828, genus: "Malurus", species: "lamberti", description: "Variegated Fairy-wren"},
"Malurus cyaneus": {id: 829, genus: "Malurus", species: "cyaneus", description: "Superb Fairy-wren"},
"Malurus leucopterus": {id: 830, genus: "Malurus", species: "leucopterus", description: "White-winged Fairy-wren"},
"Malurus amabilis": {id: 831, genus: "Malurus", species: "amabilis", description: "Lovely Fairy-wren"},
"Malurus coronatus": {id: 832, genus: "Malurus", species: "coronatus", description: "Purple-crowned Fairy-wren"},
"Sternula nereis": {id: 833, genus: "Sternula", species: "nereis", description: "Fairy Tern"},
"Sternula albifrons": {id: 834, genus: "Sternula", species: "albifrons", description: "Little Tern"},
"Thalasseus bengalensis": {id: 835, genus: "Thalasseus", species: "bengalensis", description: "Lesser Crested Tern"},
"Thalasseus bergii": {id: 836, genus: "Thalasseus", species: "bergii", description: "Crested Tern"},
"Rhipidura rufiventris": {id: 837, genus: "Rhipidura", species: "rufiventris", description: "Northern Fantail"},
"Rhipidura leucophrys": {id: 838, genus: "Rhipidura", species: "leucophrys", description: "Willie Wagtail"},
"Rhipidura phasiana": {id: 839, genus: "Rhipidura", species: "phasiana", description: "Mangrove Grey Fantail"},
"Rhipidura fuliginosa": {id: 840, genus: "Rhipidura", species: "fuliginosa", description: "New Zealand Fantail"},
"Rhipidura rufifrons": {id: 841, genus: "Rhipidura", species: "rufifrons", description: "Rufous Fantail"},
"Rhipidura albiscapa": {id: 842, genus: "Rhipidura", species: "albiscapa", description: "Grey Fantail"},
"Rhipidura dryas": {id: 843, genus: "Rhipidura", species: "dryas", description: "Arafura Fantail"},
"Cyclopsitta diophthalma": {id: 844, genus: "Cyclopsitta", species: "diophthalma", description: "Double-eyed Fig-Parrot"},
"Daption capense": {id: 845, genus: "Daption", species: "capense", description: "Cape Petrel"},
"Ixobrychus cinnamomeus": {id: 846, genus: "Ixobrychus", species: "cinnamomeus", description: "Cinnamon Bittern"},
"Ixobrychus dubius": {id: 847, genus: "Ixobrychus", species: "dubius", description: "Australian Little Bittern"},
"Ixobrychus flavicollis": {id: 848, genus: "Ixobrychus", species: "flavicollis", description: "Black Bittern"},
"Ixobrychus sinensis": {id: 849, genus: "Ixobrychus", species: "sinensis", description: "Yellow Bittern"},
"Ixobrychus eurhythmus": {id: 850, genus: "Ixobrychus", species: "eurhythmus", description: "Schrenk's Bittern"},
"Pedionomus torquatus": {id: 851, genus: "Pedionomus", species: "torquatus", description: "Plains-wanderer"},
"Gygis alba": {id: 852, genus: "Gygis", species: "alba", description: "White Tern"},
"Cyanoptila cyanomelana": {id: 853, genus: "Cyanoptila", species: "cyanomelana", description: "Blue-and-White Flycatcher"},
"Zosterops citrinella": {id: 854, genus: "Zosterops", species: "citrinella", description: "Pale White-eye"},
"Zosterops tenuirostris": {id: 855, genus: "Zosterops", species: "tenuirostris", description: "Slender-billed White-eye"},
"Zosterops luteus": {id: 856, genus: "Zosterops", species: "luteus", description: "Yellow White-eye"},
"Zosterops albogularis": {id: 857, genus: "Zosterops", species: "albogularis", description: "White-chested White-eye"},
"Zosterops natalis": {id: 858, genus: "Zosterops", species: "natalis", description: "Christmas Island White-eye"},
"Zosterops strenuus": {id: 859, genus: "Zosterops", species: "strenuus", description: "Robust White-eye"},
"Zosterops lateralis": {id: 860, genus: "Zosterops", species: "lateralis", description: "Silvereye"},
"Phoebetria fusca": {id: 861, genus: "Phoebetria", species: "fusca", description: "Sooty Albatross"},
"Phoebetria palpebrata": {id: 862, genus: "Phoebetria", species: "palpebrata", description: "Light-mantled Sooty Albatross"},
"Cladorhynchus leucocephalus": {id: 863, genus: "Cladorhynchus", species: "leucocephalus", description: "Banded Stilt"},
"Chionis minor": {id: 864, genus: "Chionis", species: "minor", description: "Black-faced Sheathbill"},
};
